# Generated by Django 5.2.17 on 2026-08-25 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.TextField()),
                ('event_version', models.SmallIntegerField(default=1)),
                ('source_module', models.TextField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('payroll', 'Payroll'), ('banking', 'Banking'), ('assets', 'Assets'), ('migration', 'Migration'), ('manual', 'Manual')])),
                ('source_document_type', models.TextField()),
                ('source_document_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('accounting_date', models.DateField()),
                ('idempotency_key', models.TextField()),
                ('payload', models.JSONField()),
                ('capability_snapshot', models.JSONField()),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posting_error', models.JSONField(blank=True, null=True)),
                ('actor_user_id', models.UUIDField()),
                ('request_id', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'accounting_event',
                'indexes': [models.Index(fields=['tenant', 'company', 'accounting_date'], name='acc_event_scope_idx'), models.Index(fields=['company', 'actor_user_id', 'occurred_at'], name='acc_event_actor_idx'), models.Index(fields=['source_document_type', 'source_document_id'], name='acc_event_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'idempotency_key'), name='accounting_event_idempotent'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'posted', 'failed', 'superseded'])), name='accounting_event_status_valid'), models.CheckConstraint(condition=models.Q(('source_module__in', ['sales', 'purchases', 'payroll', 'banking', 'assets', 'migration', 'manual'])), name='accounting_event_source_module_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'posted'), _negated=True), ('posted_at__isnull', False), _connector='OR'), name='accounting_event_posted_has_timestamp'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'failed'), _negated=True), ('posting_error__isnull', False), _connector='OR'), name='accounting_event_failed_has_reason')],
            },
        ),
            run_sql_file(
            "0034_accounting_events",
            up_sha256="1c42c2afcffb70275f82f515d73c68981479d3472eb4015cf124694f545c622f",
            down_sha256="a910b14eef09e8e947e913bdba9bb631ffffef8f1f93fa1a5d728d1d5079dce9",
        ),
    ]
