# Generated by Django 5.2.17 on 2026-08-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_events', '0001_initial'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountingevent',
            name='accounting_event_source_module_valid',
        ),
        migrations.AlterField(
            model_name='accountingevent',
            name='source_module',
            field=models.TextField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('payroll', 'Payroll'), ('banking', 'Banking'), ('assets', 'Assets'), ('migration', 'Migration'), ('manual', 'Manual'), ('periods', 'Periods')]),
        ),
        migrations.AddConstraint(
            model_name='accountingevent',
            constraint=models.CheckConstraint(condition=models.Q(('source_module__in', ['sales', 'purchases', 'payroll', 'banking', 'assets', 'migration', 'manual', 'periods'])), name='accounting_event_source_module_valid'),
        ),
    ]
