"""`treasury` joins the source vocabulary -- ADR-073 §5, `F2.A2`.

The third addition, on the pattern of the two before it (`periods`,
`production`): a value names **the source of the fact**, not an app. Money moving
is not `banking` -- that one names the bank statement, a different source of the
same kind of fact, arriving with the importer. A cash receipt typed by hand has
never been near a bank.

Additive: the CHECK is dropped and recreated with one more value, and no existing
row changes meaning.
"""

# Generated by Django 5.2.17 on 2026-08-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_events', '0003_production_source_module'),
        ('tenancy', '0011_provision_company_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountingevent',
            name='accounting_event_source_module_valid',
        ),
        migrations.AlterField(
            model_name='accountingevent',
            name='source_module',
            field=models.TextField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('payroll', 'Payroll'), ('banking', 'Banking'), ('assets', 'Assets'), ('migration', 'Migration'), ('manual', 'Manual'), ('periods', 'Periods'), ('treasury', 'Treasury'), ('production', 'Production')]),
        ),
        migrations.AddConstraint(
            model_name='accountingevent',
            constraint=models.CheckConstraint(condition=models.Q(('source_module__in', ['sales', 'purchases', 'payroll', 'banking', 'assets', 'migration', 'manual', 'periods', 'treasury', 'production'])), name='accounting_event_source_module_valid'),
        ),
    ]
