"""The fiscal status the event stood on -- ADR-088.

Nullable and additive (`C5`), and the nullability carries meaning rather than
convenience: an event written before this column existed has no stamp, and that is
a different fact from "the company had no statuses". Backfilling from
`company_vat_registration` would be possible and would be a lie -- it would claim
the engine read something it never read.

No paired SQL: a column on a table whose policy and grants already exist.
"""

# Generated by Django 5.2.17 on 2026-08-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_events', '0004_treasury_source_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingevent',
            name='tax_status_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
