# Generated by Django 5.2.17 on 2026-08-25 08:10

import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0005_resolver_grant"),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_type', models.TextField(choices=[('bnm_official', 'Bnm Official'), ('manual', 'Manual'), ('contractual', 'Contractual')])),
                ('source', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exchange_rate',
                'indexes': [models.Index(fields=['currency', 'rate_date'], name='exchange_rate_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date', 'rate_type'), name='exchange_rate_unique'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_positive'), models.CheckConstraint(condition=models.Q(('rate_type__in', ['bnm_official', 'manual', 'contractual'])), name='exchange_rate_type_valid')],
            },
        ),
            run_sql_file(
            "0029_exchange_rate",
            up_sha256="db752298548193669f001c7876b878b4cf6caf90b91bbe9906b277da02c6b812",
            down_sha256="8ecee5c308fdd8f5987661c97bd5b4d61d687ce99bafccd8f9dcde849ebfa6e8",
        ),
    ]
