"""Sales-side document types over the document core.

REVERSIBILITY = "reversible-tested"

Three tables, each one-to-one with a row in `document`, carrying only what is
theirs. No account, no correspondence, no dimension (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 07:41

import django.db.models.deletion
from django.db import migrations, models


from evidenta.platform.rls.sql import run_sql_file

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_layer'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_order', serialize=False, to='documents.document')),
                ('requested_delivery_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'customer_order',
                'indexes': [models.Index(fields=['tenant', 'company', 'requested_delivery_date'], name='customer_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProformaDocument',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proforma', serialize=False, to='documents.document')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'proforma_document',
                'indexes': [models.Index(fields=['tenant', 'company', 'valid_until'], name='proforma_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesDocument',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sales', serialize=False, to='documents.document')),
                ('nature', models.TextField(choices=[('delivery', 'Delivery'), ('advance', 'Advance')], default='delivery')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sales_document',
                'indexes': [models.Index(fields=['tenant', 'company', 'nature'], name='sales_document_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nature__in', ['delivery', 'advance'])), name='sales_document_nature_valid')],
            },
        ),
    
        run_sql_file(
            "0054_sales_documents",
            up_sha256="eb1d58c8fdd100b8110955f2839db97b45f61821f3f61867f31c3a40b128a217",
            down_sha256="4554a627aa5f7062e50630dd8f9e7906f18ae37576f6139ffd36669c5e97feb9",
        ),
    ]
