"""What is sold, and to whom -- the two discriminators the posting asks for.

ADR-073 §2 and §3. Both defaults here are **one-off**: `preserve_default=False`
keeps them out of the model and out of the database, because neither question has
a safe answer. A `revenue_kind` defaulting to services would post a sale of goods
to the services account; a `partner_resident` defaulting to true would post a
receivable from a non-resident to the domestic account -- balanced, `R11` green,
and wrong in the balance sheet at every reporting date.
"""

# Generated by Django 5.2.17 on 2026-08-31 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rate_term'),
        ('sales', '0001_initial'),
        ('tenancy', '0008_company_classifier_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdocument',
            name='partner_resident',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdocument',
            name='revenue_kind',
            field=models.TextField(choices=[('services', 'Services'), ('goods', 'Goods'), ('products', 'Products')], default='services'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='salesdocument',
            constraint=models.CheckConstraint(condition=models.Q(('revenue_kind__in', ['services', 'goods', 'products'])), name='sales_document_revenue_kind_valid'),
        ),
    ]
