"""`return` joins the sale's natures -- ADR-073 §7.

A credit note is a sales document with a third nature, not a `ReversalDocument`:
a reversal cancels an error, a return is a new economic event with the same lines
and the same lifecycle as the delivery it answers.

Additive: the CHECK is dropped and recreated with one more value, and no existing
row changes meaning. Nothing is backfilled -- every document written so far is a
delivery or an advance, and still is.
"""

# Generated by Django 5.2.17 on 2026-08-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_rate_term'),
        ('sales', '0002_revenue_kind_and_residence'),
        ('tenancy', '0011_provision_company_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesdocument',
            name='sales_document_nature_valid',
        ),
        migrations.AlterField(
            model_name='salesdocument',
            name='nature',
            field=models.TextField(choices=[('delivery', 'Delivery'), ('advance', 'Advance'), ('return', 'Return')], default='delivery'),
        ),
        migrations.AddConstraint(
            model_name='salesdocument',
            constraint=models.CheckConstraint(condition=models.Q(('nature__in', ['delivery', 'advance', 'return'])), name='sales_document_nature_valid'),
        ),
    ]
