"""The unified monthly return, versioned from the first day.

Art. 5 para (1) of Law 489/1999 makes the nominal record and the contribution
calculation *parts of* the return, so this is one header with two sections rather
than three objects to keep in step.

Two things here are **form** and therefore cannot be added later: the versioning
(art. 188 -- a correction is a corrected return, never an overwrite) and the fact
that the rows are stored rather than recomputed. Both would be migrations over
artefacts already transmitted.

The SQL carries the collations, the freeze trigger -- a submitted return's rows
never change -- and the privileges, which withdraw DELETE on the header
explicitly rather than by omitting it from a GRANT (`OD-105`, third occurrence).
"""

# Generated by Django 5.2.17 on 2026-08-30 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0008_company_classifier_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpcDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('version_number', models.IntegerField()),
                ('fiscal_code', models.TextField()),
                ('cuatm_code', models.TextField(blank=True, null=True)),
                ('caem_code', models.TextField(blank=True, null=True)),
                ('due_on', models.DateField()),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft')),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('corrects', models.ForeignKey(blank=True, db_column='corrects_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrected_by', to='tax.ipcdeclaration')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ipc_declaration',
            },
        ),
        migrations.CreateModel(
            name='IpcNominalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.IntegerField()),
                ('person_id', models.UUIDField()),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('idnp', models.TextField(blank=True, null=True)),
                ('personal_insurance_code', models.TextField(blank=True, null=True)),
                ('work_period_start', models.DateField()),
                ('work_period_end', models.DateField()),
                ('insured_category_code', models.TextField(blank=True, null=True)),
                ('tariff_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('insured_income', models.DecimalField(decimal_places=2, max_digits=18)),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('declaration', models.ForeignKey(db_column='declaration_id', on_delete=django.db.models.deletion.CASCADE, related_name='nominal', to='tax.ipcdeclaration')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ipc_nominal_line',
            },
        ),
        migrations.CreateModel(
            name='IpcTotalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('income_source_code', models.TextField()),
                ('cas_tariff_code', models.TextField()),
                ('income_paid', models.DecimalField(decimal_places=2, max_digits=18)),
                ('income_tax_withheld', models.DecimalField(decimal_places=2, max_digits=18)),
                ('health_insurance_withheld', models.DecimalField(decimal_places=2, max_digits=18)),
                ('social_contribution', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('declaration', models.ForeignKey(db_column='declaration_id', on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='tax.ipcdeclaration')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'ipc_total_line',
            },
        ),
        migrations.AddIndex(
            model_name='ipcdeclaration',
            index=models.Index(fields=['tenant', 'company', 'year', 'month'], name='ipc_declaration_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipcdeclaration',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month', 'version_number'), name='ipc_declaration_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='ipcdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='ipc_declaration_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='ipcdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='ipc_declaration_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='ipcdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('version_number', 1), ('corrects__isnull', True)), models.Q(('version_number__gt', 1), ('corrects__isnull', False)), _connector='OR'), name='ipc_declaration_correction_chain'),
        ),
        migrations.AddConstraint(
            model_name='ipcdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'submitted'), _negated=True), ('submitted_on__isnull', False), _connector='OR'), name='ipc_declaration_submitted_has_a_date'),
        ),
        migrations.AddConstraint(
            model_name='ipcdeclaration',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'submitted'])), name='ipc_declaration_status_valid'),
        ),
        migrations.AddIndex(
            model_name='ipcnominalline',
            index=models.Index(fields=['declaration', 'person_id'], name='ipc_nominal_person_idx'),
        ),
        migrations.AddConstraint(
            model_name='ipcnominalline',
            constraint=models.UniqueConstraint(fields=('declaration', 'person_id'), name='ipc_nominal_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='ipcnominalline',
            constraint=models.UniqueConstraint(fields=('declaration', 'line_number'), name='ipc_nominal_line_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='ipcnominalline',
            constraint=models.CheckConstraint(condition=models.Q(('insured_income__gte', 0), ('contribution__gte', 0)), name='ipc_nominal_line_amounts_positive'),
        ),
        migrations.AddConstraint(
            model_name='ipcnominalline',
            constraint=models.CheckConstraint(condition=models.Q(('work_period_end__gte', models.F('work_period_start'))), name='ipc_nominal_line_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='ipctotalline',
            constraint=models.UniqueConstraint(fields=('declaration', 'income_source_code', 'cas_tariff_code'), name='ipc_total_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='ipctotalline',
            constraint=models.CheckConstraint(condition=models.Q(('income_paid__gte', 0), ('income_tax_withheld__gte', 0), ('health_insurance_withheld__gte', 0), ('social_contribution__gte', 0)), name='ipc_total_line_amounts_positive'),
        ),
        run_sql_file(
            "0069_ipc_declaration",
            up_sha256="c713b71855b3632da5134b29265be979805f2afe8b12648dabb64727a64fd1ea",
            down_sha256="98eef6fc59f5b7a9273cb4602de10351b51bc37cb903b7c3c4514b7d8d94c17e",
        ),
    ]
