"""People, work relationships and the timesheet -- the general regime.

Five tables, all company-scoped: the legal employer is the **company**, not the
tenant (ADR-065 section 4). Policy SQL lands in the same transaction as the
tables (`C30`), and the collations follow `C34` -- IDNP, document numbers,
contract and order numbers, the CAS category code and the clause letter are
codes; names and the position title are names.

`relationship_type` is the foreign key ADR-071 exists for: with a string somebody
writes `orice_bază_CAS` and the defect is back, with a key a domain that does not
exist never reaches the table. `NOT NULL`, no default (`C1(b)`).

The timesheet day carries a freeze trigger on its month, on the same pattern as
document contents following their document: a day edited after the month closed
changes a result already reported.
"""

# Generated by Django 5.2.17 on 2026-08-30 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal_registry', '0002_employment_relationship_type'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('idnp', models.TextField(blank=True, null=True)),
                ('identity_document_type', models.TextField(blank=True, null=True)),
                ('identity_document_number', models.TextField(blank=True, null=True)),
                ('tax_residency', models.TextField(choices=[('resident', 'Resident'), ('non_resident', 'Non Resident')])),
                ('social_insurance_code', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.TextField()),
                ('signed_on', models.DateField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('hire_order_number', models.TextField()),
                ('hire_order_date', models.DateField()),
                ('termination_order_number', models.TextField(blank=True, null=True)),
                ('termination_order_date', models.DateField(blank=True, null=True)),
                ('position_title', models.TextField()),
                ('base_salary', models.DecimalField(decimal_places=4, max_digits=18)),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cas_payer_point', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='payroll.employee')),
                ('relationship_type', models.ForeignKey(db_column='relationship_type', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='fiscal_registry.employmentrelationshiptype')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'employment_contract',
            },
        ),
        migrations.CreateModel(
            name='EmploymentContractAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.TextField()),
                ('signed_on', models.DateField()),
                ('effective_from', models.DateField()),
                ('order_number', models.TextField()),
                ('order_date', models.DateField()),
                ('changed_clause', models.TextField()),
                ('note', models.TextField(blank=True, default='')),
                ('position_title', models.TextField(blank=True, null=True)),
                ('base_salary', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='payroll.employmentcontract')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'employment_contract_amendment',
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('norm_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.TextField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'timesheet',
            },
        ),
        migrations.CreateModel(
            name='TimesheetDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_days', to='payroll.employmentcontract')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('timesheet', models.ForeignKey(db_column='timesheet_id', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='payroll.timesheet')),
            ],
            options={
                'db_table': 'timesheet_day',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'company', 'last_name'], name='employee_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('tax_residency__in', ['resident', 'non_resident'])), name='employee_residency_valid'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idnp__isnull', False), ('identity_document_type__isnull', True), ('identity_document_number__isnull', True)), models.Q(('idnp__isnull', True), ('identity_document_type__isnull', False), ('identity_document_number__isnull', False)), _connector='OR'), name='employee_exactly_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('idnp__isnull', False)), fields=('company', 'idnp'), name='employee_idnp_unique'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('idnp__isnull', True)), fields=('company', 'identity_document_type', 'identity_document_number'), name='employee_document_unique'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['tenant', 'company', 'effective_from'], name='employment_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['employee'], name='employment_contract_emp_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.UniqueConstraint(fields=('company', 'contract_number'), name='employment_contract_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='employment_contract_term_ordered'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('ended_on__gte', models.F('effective_from')), _connector='OR'), name='employment_contract_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('base_salary__gte', 0)), name='employment_contract_salary_positive'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours__gt', 0)), name='employment_contract_hours_positive'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('cas_payer_point__in', ('1.1', '1.2', '1.4', '1.5'))), name='employment_contract_cas_point_valid'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), models.Q(('termination_order_number__isnull', False), ('termination_order_date__isnull', False)), _connector='OR'), name='employment_contract_end_has_an_order'),
        ),
        migrations.AddIndex(
            model_name='employmentcontractamendment',
            index=models.Index(fields=['contract', 'effective_from'], name='employment_amendment_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontractamendment',
            constraint=models.UniqueConstraint(fields=('contract', 'amendment_number'), name='employment_amendment_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontractamendment',
            constraint=models.CheckConstraint(condition=models.Q(('changed_clause', ''), _negated=True), name='employment_amendment_has_clause'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontractamendment',
            constraint=models.CheckConstraint(condition=models.Q(('base_salary__isnull', True), ('base_salary__gte', 0), _connector='OR'), name='employment_amendment_salary_positive'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontractamendment',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours__isnull', True), ('weekly_hours__gt', 0), _connector='OR'), name='employment_amendment_hours_positive'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['tenant', 'company', 'year', 'month'], name='timesheet_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='timesheet_month_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='timesheet_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(condition=models.Q(('norm_hours__gt', 0)), name='timesheet_norm_positive'),
        ),
        migrations.AddConstraint(
            model_name='timesheet',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'closed'])), name='timesheet_status_valid'),
        ),
        migrations.AddIndex(
            model_name='timesheetday',
            index=models.Index(fields=['tenant', 'company', 'work_date'], name='timesheet_day_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheetday',
            index=models.Index(fields=['timesheet', 'contract'], name='timesheet_day_contract_idx'),
        ),
        migrations.AddConstraint(
            model_name='timesheetday',
            constraint=models.UniqueConstraint(fields=('contract', 'work_date'), name='timesheet_day_unique'),
        ),
        migrations.AddConstraint(
            model_name='timesheetday',
            constraint=models.CheckConstraint(condition=models.Q(('hours_worked__gte', 0), ('hours_worked__lte', 24)), name='timesheet_day_hours_in_a_day'),
        ),
        migrations.AddConstraint(
            model_name='timesheetday',
            constraint=models.CheckConstraint(condition=models.Q(('night_hours__gte', 0), ('night_hours__lte', models.F('hours_worked'))), name='timesheet_day_night_within_worked'),
        ),
        migrations.AddConstraint(
            model_name='timesheetday',
            constraint=models.CheckConstraint(condition=models.Q(('holiday_hours__gte', 0), ('holiday_hours__lte', models.F('hours_worked'))), name='timesheet_day_holiday_within_worked'),
        ),
        run_sql_file(
            "0064_payroll_people_and_timesheet",
            up_sha256="d9ee2072ef229f26f6557615541b468d9f605659f045cdabfdd3ee05d5b7c0c6",
            down_sha256="3e527664c21b3068895328745315a04cf544561592474fae1b73c84e56531b6e",
        ),
    ]
