"""Income tax exemptions -- an application with an effective date, not a flag.

Point 18 of the regulation approved by HG 697/2014 grants and cancels exemptions
*from the month following* the one the application was filed or withdrawn in, so
what has to be stored is a history rather than a state: `R18` asks every
recalculation of a past month what was in force **then**, and a boolean on the
employee cannot answer it.

Three things land in SQL rather than in the model, each because Django cannot
express it: point 18 as a CHECK over `filed_on` and `effective_from`; the overlap
`EXCLUDE` that refuses the same dependent twice for one employee while leaving
two employees free to claim for the same person; and the privileges, which grant
no DELETE on entitlements -- a closed exemption is closed with a date, never
removed.
"""

# Generated by Django 5.2.17 on 2026-08-30 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('idnp', models.TextField(blank=True, null=True)),
                ('identity_document_type', models.TextField(blank=True, null=True)),
                ('identity_document_number', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='payroll.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'exemption_dependent',
            },
        ),
        migrations.CreateModel(
            name='ExemptionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filed_on', models.DateField()),
                ('effective_from', models.DateField()),
                ('declared_sole_workplace', models.BooleanField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='exemption_applications', to='payroll.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'exemption_application',
            },
        ),
        migrations.CreateModel(
            name='ExemptionEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(choices=[('P', 'Personal'), ('M', 'Personal Major'), ('Sm', 'Spouse Major'), ('N', 'Dependent'), ('H', 'Dependent Disabled')])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('dependent', models.ForeignKey(blank=True, db_column='dependent_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='payroll.dependent')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='exemptions', to='payroll.employee')),
                ('granted_by', models.ForeignKey(db_column='granted_by_id', on_delete=django.db.models.deletion.PROTECT, related_name='granted', to='payroll.exemptionapplication')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('withdrawn_by', models.ForeignKey(blank=True, db_column='withdrawn_by_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn', to='payroll.exemptionapplication')),
            ],
            options={
                'db_table': 'exemption_entitlement',
            },
        ),
        migrations.AddIndex(
            model_name='dependent',
            index=models.Index(fields=['tenant', 'company', 'employee'], name='dependent_idx'),
        ),
        migrations.AddConstraint(
            model_name='dependent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('idnp__isnull', False), ('identity_document_type__isnull', True), ('identity_document_number__isnull', True)), models.Q(('idnp__isnull', True), ('identity_document_type__isnull', False), ('identity_document_number__isnull', False)), _connector='OR'), name='dependent_exactly_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='dependent',
            constraint=models.UniqueConstraint(condition=models.Q(('idnp__isnull', False)), fields=('employee', 'idnp'), name='dependent_idnp_unique'),
        ),
        migrations.AddIndex(
            model_name='exemptionapplication',
            index=models.Index(fields=['tenant', 'company', 'employee', 'effective_from'], name='exemption_application_idx'),
        ),
        migrations.AddIndex(
            model_name='exemptionentitlement',
            index=models.Index(fields=['tenant', 'company', 'employee', 'valid_from'], name='exemption_entitlement_idx'),
        ),
        migrations.AddConstraint(
            model_name='exemptionentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('code__in', ['P', 'M', 'Sm', 'N', 'H'])), name='exemption_code_valid'),
        ),
        migrations.AddConstraint(
            model_name='exemptionentitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code__in', ('N', 'H')), ('dependent__isnull', False)), models.Q(models.Q(('code__in', ('N', 'H')), _negated=True), ('dependent__isnull', True)), _connector='OR'), name='exemption_dependent_matches_code'),
        ),
        migrations.AddConstraint(
            model_name='exemptionentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='exemption_period_valid'),
        ),
        run_sql_file(
            "0065_payroll_exemptions",
            up_sha256="c7ee7c69c255e265d958b7f2272a17c118400cb976566d1b8728f34b3c02706f",
            down_sha256="6d99b566fe3fd9316002c6941673b752369c980765c6bb588b2f6cc5a4975d1d",
        ),
    ]
