"""The monthly payroll run and its lines.

Two dates on every line (ADR-065 section 6): the **work period**, which the
nominal declaration reads, and the **accrual date**, which decides which
parameters apply. The second cannot be added later -- a posted line has no way of
finding out afterwards when it accrued.

Three things land in SQL: the freeze trigger, which makes an approved run's lines
unchangeable; the collations on the two code columns; and the privileges, which
withdraw DELETE on the run explicitly rather than by omitting it from a GRANT
(`OD-105`, second occurrence in this module).

`budget_funded_employer` arrives on the contract with a **one-off** default: the
column has to be addable, and `preserve_default=False` keeps the default out of
both the database and the model. Annex 1 point 1.1 carries 29% budgetary against
24% private, and a boolean that defaulted to `false` would quietly apply the
private rate to every budget-funded employer.
"""

# Generated by Django 5.2.17 on 2026-08-30 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_exemptions'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentcontract',
            name='budget_funded_employer',
            # The default is one-off: it exists so the column can be added, not
            # so a row can arrive without anyone deciding. `preserve_default=False`
            # is what keeps it out of the database and out of the model.
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('accrual_date', models.DateField()),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft')),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('timesheet', models.ForeignKey(db_column='timesheet_id', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='payroll.timesheet')),
            ],
            options={
                'db_table': 'payroll_run',
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nature', models.TextField(choices=[('salary_accrual', 'Salary Accrual'), ('employer_charge', 'Employer Charge'), ('employee_withholding', 'Employee Withholding')])),
                ('component_key', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unresolved_reason', models.TextField(blank=True, null=True)),
                ('basis', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('parameter_id', models.UUIDField(blank=True, null=True)),
                ('parameter_key', models.TextField(blank=True, null=True)),
                ('work_period_start', models.DateField()),
                ('work_period_end', models.DateField()),
                ('accrual_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('contract', models.ForeignKey(db_column='contract_id', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.employmentcontract')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lines', to='payroll.employee')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
            ],
            options={
                'db_table': 'payroll_line',
            },
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['tenant', 'company', 'year', 'month'], name='payroll_run_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(fields=('company', 'year', 'month'), name='payroll_run_month_unique'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='payroll_run_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved'])), name='payroll_run_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'approved'), _negated=True), ('approved_by_user_id__isnull', False), _connector='OR'), name='payroll_run_approved_has_an_approver'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['tenant', 'company', 'accrual_date'], name='payroll_line_accrual_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollline',
            index=models.Index(fields=['run', 'employee'], name='payroll_line_employee_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('nature__in', ['salary_accrual', 'employer_charge', 'employee_withholding'])), name='payroll_line_nature_valid'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', False), ('unresolved_reason__isnull', True)), models.Q(('amount__isnull', True), ('unresolved_reason__isnull', False)), _connector='OR'), name='payroll_line_amount_or_reason'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='payroll_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.CheckConstraint(condition=models.Q(('work_period_end__gte', models.F('work_period_start'))), name='payroll_line_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='payrollline',
            constraint=models.UniqueConstraint(fields=('run', 'contract', 'component_key'), name='payroll_line_unique'),
        ),
        run_sql_file(
            "0066_payroll_run",
            up_sha256="15ecc66ec01d342b23be74c53ca5f7fbcbbe7ba41e90a91d4b5d40280e08a0d7",
            down_sha256="155f46ba88ac605064240fa32deb5f0c52a9837aa2122808792174052b99b928",
        ),
    ]
