# Generated by Django 5.2.17 on 2026-08-25 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("numbering", "0001_initial"),
        ('identity', '0006_remove_user_mfa_secret_encrypted_mfabackupcode_and_more'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('company_id', models.UUIDField()),
                ('document_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField()),
                ('event_type', models.TextField()),
                ('from_state', models.TextField(blank=True, null=True)),
                ('to_state', models.TextField(blank=True, null=True)),
                ('actor_user_id', models.UUIDField()),
                ('request_id', models.TextField()),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_event',
                'indexes': [models.Index(fields=['tenant_id', 'company_id', 'occurred_at'], name='document_event_scope_idx'), models.Index(fields=['document_id', 'occurred_at'], name='document_event_doc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.TextField()),
                ('series', models.TextField(default='')),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('formatted_number', models.TextField(blank=True, null=True)),
                ('fiscal_year', models.SmallIntegerField(blank=True, null=True)),
                ('document_date', models.DateField()),
                ('state', models.TextField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('posted', 'Posted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft')),
                ('currency', models.CharField(default='MDL', max_length=3)),
                ('partner_id', models.UUIDField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('confirmed_by', models.ForeignKey(blank=True, db_column='confirmed_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_confirmed', to='identity.user')),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='documents_created', to='identity.user')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'document',
                'indexes': [models.Index(fields=['tenant', 'company', 'document_date'], name='document_scope_idx'), models.Index(fields=['company', 'document_type', 'state'], name='document_state_idx'), models.Index(fields=['company', 'partner_id'], name='document_partner_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'confirmed', 'posted', 'completed', 'cancelled'])), name='document_state_valid'), models.CheckConstraint(condition=models.Q(models.Q(('fiscal_year__isnull', True), ('number__isnull', True)), models.Q(('fiscal_year__isnull', False), ('number__isnull', False)), _connector='OR'), name='document_number_complete'), models.CheckConstraint(condition=models.Q(models.Q(('state', 'draft'), _negated=True), ('number__isnull', True), _connector='OR'), name='document_draft_has_no_number'), models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('company', 'document_type', 'series', 'fiscal_year', 'number'), name='document_number_unique')],
            },
        ),
        run_sql_file(
            "0024_documents",
            up_sha256="c878f1481807232209b445fd5e354a2c5769e58ed63e17bfb16f14c8255657b1",
            down_sha256="d9075f91f838a3aedb4a5ff5f3be3b1c21927394273f86e1c681fc3878c247c8",
        ),
    ]
