"""The document layer: positions, storno, the frozen document, the second date.

REVERSIBILITY = "reversible-tested"

REVERSIBILITY = "reversible-tested"

`accounting_date` arrives nullable, is backfilled from `document_date`, and is
then made NOT NULL. Immutability of a validated document is a trigger, not a
service: a bulk import, a data migration and a psql session all bypass every
service ever written, and that is exactly where a validated document gets
quietly edited. No posted accounting data is touched (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 07:41

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('identity', '0007_session_token'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('item_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit_id', models.UUIDField(blank=True, null=True)),
                ('unit_code', models.TextField(default='')),
                ('unit_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('vat_regime_code', models.TextField()),
                ('vat_rate_key', models.TextField(blank=True, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=4, max_digits=9)),
                ('vat_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_line',
            },
        ),
        migrations.CreateModel(
            name='ReversalDocument',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reversal', serialize=False, to='documents.document')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reversal_document',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='accounting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, db_column='cancelled_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents_cancelled', to='identity.user'),
        ),
        migrations.AddField(
            model_name='document',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='document',
            name='external_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='numbering_regime',
            field=models.TextField(choices=[('own', 'Own'), ('external', 'External')], default='own'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_document',
            field=models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_documents', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['source_document'], name='document_source_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'company', 'accounting_date'], name='document_accounting_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('numbering_regime__in', ['own', 'external'])), name='document_regime_valid'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('numbering_regime', 'external'), _negated=True), ('number__isnull', True), _connector='OR'), name='document_external_has_no_own_number'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['draft', 'cancelled']), ('numbering_regime', 'external'), ('number__isnull', False), _connector='OR'), name='document_own_regime_is_numbered_when_validated'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'cancelled'), _negated=True), ('cancellation_reason__isnull', False), _connector='OR'), name='document_cancelled_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='document_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('external_number__isnull', False)), fields=('company', 'document_type', 'external_number'), name='document_external_number_unique'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='source_line',
            field=models.ForeignKey(blank=True, db_column='source_line_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_lines', to='documents.documentline'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='reversaldocument',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='reversaldocument',
            name='reversed_document',
            field=models.ForeignKey(db_column='reversed_document_id', on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='documents.document'),
        ),
        migrations.AddField(
            model_name='reversaldocument',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='documentline',
            index=models.Index(fields=['tenant', 'company', 'document'], name='document_line_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='documentline',
            index=models.Index(fields=['company', 'item_id'], name='document_line_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.UniqueConstraint(fields=('document', 'line_no'), name='document_line_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('line_no__gte', 1)), name='document_line_position_positive'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='document_line_quantity_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('net_amount'), '+', models.F('vat_amount')))), name='document_line_total_is_net_plus_vat'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), _connector='OR'), name='document_line_discount_percent_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('vat_rate__gte', 0)), name='document_line_vat_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='documentline',
            constraint=models.CheckConstraint(condition=models.Q(('vat_regime_code', ''), _negated=True), name='document_line_has_a_vat_regime'),
        ),
        migrations.AddIndex(
            model_name='reversaldocument',
            index=models.Index(fields=['tenant', 'company', 'reversed_document'], name='reversal_document_idx'),
        ),
        migrations.AddConstraint(
            model_name='reversaldocument',
            constraint=models.UniqueConstraint(fields=('reversed_document',), name='reversal_document_once'),
        ),
        migrations.AddConstraint(
            model_name='reversaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('document', models.F('reversed_document')), _negated=True), name='reversal_document_not_itself'),
        ),
        migrations.AddConstraint(
            model_name='reversaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='reversal_document_has_a_reason'),
        ),
    
        run_sql_file(
            "0051_document_layer",
            up_sha256="2c45f882b831c55d25b55d175c61a0711c8649f10ba78316e4485c67800a067f",
            down_sha256="539db5f48fffffa77a3ee3c8e42d0f931f232fd967d8c496572f65584eb498c5",
        ),
        # After the backfill inside the file above. `SET NOT NULL` scans the
        # table physically, so a row with no accounting date fails it loudly
        # instead of being given one nobody chose.
        migrations.AlterField(
            model_name='document',
            name='accounting_date',
            field=models.DateField(),
        ),
    ]
