# Generated by Django 5.2.17 on 2026-08-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_layer'),
        ('identity', '0007_session_token'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rate_term',
            field=models.TextField(choices=[('payment_date', 'Payment Date'), ('delivery_date', 'Delivery Date'), ('fixed', 'Fixed')], default='payment_date'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('rate_term__in', ['payment_date', 'delivery_date', 'fixed'])), name='document_rate_term_valid'),
        ),
    ]
