# Generated by Django 5.2.17 on 2026-08-25 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal_parameters', '0001_initial'),
        # The policy SQL below touches all three fiscal tables, two of which
        # belong to `fiscal_parameters`. Table and policy land in one transaction
        # (ADR-012), so the migration that carries the SQL has to be the last of
        # the three to run -- not the first that happened to be convenient.
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalLogicVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logic_key', models.TextField()),
                ('implementation_ref', models.TextField()),
                ('version', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('regression_case_set', models.TextField()),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft')),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal_parameters.fiscalparametersource')),
            ],
            options={
                'db_table': 'fiscal_logic_version',
                'indexes': [models.Index(fields=['logic_key', 'valid_from'], name='fiscal_logic_key_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='fiscal_logic_period_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'active', 'superseded'])), name='fiscal_logic_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('approved_by_user_id__isnull', False), _connector='OR'), name='fiscal_logic_active_requires_approval'), models.UniqueConstraint(fields=('logic_key', 'version'), name='fiscal_logic_version_unique')],
            },
        ),
            run_sql_file(
            "0027_fiscal",
            up_sha256="4e2b46b66c8d9edadcc3d40c31cb18540eacdae33c17014eea74bbc08796b2ba",
            down_sha256="ecf9f660a0b75fc871ad92401f3b31cafb1d57a5962d69d776bf4ee5dd31ee58",
        ),
    ]
