"""Where an invariant applies -- one row per type, because it is a set.

`OD-106`, closed here. Art. 22 para (1) covers `employment_contract` and
`service_relationship` and not `civil_contract`; a single foreign key column
cannot express two, so the domain is rows rather than a column.

Seeded through `backfill()` with the cardinality stated (`expected=0`) and the
uniqueness constraint added in the same migration, after the write -- rule (c) of
`OD-94`. The two rows are what the payroll calculation reads in the very next
commit, so this is a schema with a consumer rather than one validated by nothing.
"""

# Generated by Django 5.2.17 on 2026-08-30 22:51

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.backfill import backfill
from evidenta.platform.rls.sql import run_sql_file


#: The invariant the payroll calculation reads, and the two types it covers.
#: Written out here rather than derived: this is the migration that *defines* the
#: domain, and a later edit to a constant must not silently mean the applied rows
#: said something else.
SEED = """
INSERT INTO calculation_invariant_domain (id, invariant_key, relationship_type) VALUES
  (gen_random_uuid(), 'cas.minimum_base_per_employee', 'employment_contract'),
  (gen_random_uuid(), 'cas.minimum_base_per_employee', 'service_relationship')
"""

UNSEED = "DELETE FROM calculation_invariant_domain"

REASON = (
    "Seeding the domain of the art. 22 minimum-base invariant. The owner has no "
    "policy on this table until the SQL above creates one, and under FORCE ROW "
    "LEVEL SECURITY a privilege without a policy sees nothing; the suspension "
    "lasts for this transaction only."
)


def seed(apps, schema_editor):
    backfill(
        schema_editor,
        "calculation_invariant_domain",
        expected=0,
        statements=SEED,
        reason=REASON,
    )


def unseed(apps, schema_editor):
    backfill(
        schema_editor,
        "calculation_invariant_domain",
        expected=2,
        statements=UNSEED,
        reason=REASON,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal_registry', '0002_employment_relationship_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationInvariantDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invariant_key', models.TextField()),
                ('relationship_type', models.ForeignKey(db_column='relationship_type', on_delete=django.db.models.deletion.PROTECT, related_name='invariant_domains', to='fiscal_registry.employmentrelationshiptype')),
            ],
            options={
                'db_table': 'calculation_invariant_domain',
                'indexes': [models.Index(fields=['invariant_key'], name='calc_invariant_domain_idx')],
            },
        ),
        run_sql_file(
            "0067_invariant_domain",
            up_sha256="32b8a75d4d9a0ded3588f8ff13604184108c48eb86f99e1d19f2d2f85f92c2a4",
            down_sha256="e4d38bc8fe863e5d065e13476751d6215ee5af6b33d0948ce8e872abb3b73d8c",
        ),
        migrations.RunPython(seed, unseed),
        migrations.AddConstraint(
            model_name="calculationinvariantdomain",
            constraint=models.UniqueConstraint(
                fields=("invariant_key", "relationship_type"),
                name="calculation_invariant_domain_unique",
            ),
        ),
    ]
