# Generated by Django 5.2.17 on 2026-08-25 05:34

from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('actor_user_id', models.UUIDField()),
                ('actor_firm_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.TextField()),
                ('action', models.TextField()),
                ('entity_type', models.TextField()),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.TextField(choices=[('web', 'Web'), ('api', 'Api'), ('task', 'Task'), ('system', 'System'), ('migration', 'Migration')])),
            ],
            options={
                'db_table': 'audit_event',
                'indexes': [models.Index(fields=['tenant_id', 'company_id', 'occurred_at'], name='audit_event_scope_idx'), models.Index(fields=['tenant_id', 'actor_user_id', 'occurred_at'], name='audit_event_actor_idx'), models.Index(fields=['tenant_id', 'entity_type', 'entity_id', 'occurred_at'], name='audit_event_entity_idx'), models.Index(fields=['request_id'], name='audit_event_request_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source__in', ['web', 'api', 'task', 'system', 'migration'])), name='audit_event_source_valid')],
            },
        ),
        run_sql_file(
            "0018_audit",
            up_sha256="36dea944014bea40982b6224a56a220ad09e50eb43fe62059923b79270cca20d",
            down_sha256="97e91e9caf9c66cec85a64a632b814f6f00653ec811f431c9bde83dec4f0e161",
        ),
    ]
