"""`support_grant` -- ADR-077 §3, with its policy, its functions and its window in one transaction.

Generated by `makemigrations` for the model, then completed by hand with the paired
SQL. Depends on identity/0011 because the redefined `rls.resolve_session` in that
SQL returns `user_session.support_grant_id`, which that migration adds; and on the
audit constraint migration, because the request function writes `P-7` rows.
"""

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0011_support_session"),
        ("tenancy", "0011_provision_company_role"),
        ("audit", "0004_paths_p11_p12"),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_ref', models.TextField()),
                ('justification', models.TextField()),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_grants_approved', to='identity.user')),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('requested_by', models.ForeignKey(db_column='requested_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='support_grants_requested', to='identity.user')),
                ('revoked_by', models.ForeignKey(blank=True, db_column='revoked_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_grants_revoked', to='identity.user')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'support_grant',
                'indexes': [models.Index(fields=['tenant', 'requested_at'], name='support_grant_tenant_idx'), models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['requested_by', 'tenant'], name='support_grant_live_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('approved_by__isnull', True)), models.Q(('approved_at__isnull', False), ('approved_by__isnull', False)), _connector='OR'), name='support_grant_approval_pair'), models.CheckConstraint(condition=models.Q(models.Q(('approved_at__isnull', True), ('expires_at__isnull', True)), models.Q(('approved_at__isnull', False), ('expires_at__isnull', False)), _connector='OR'), name='support_grant_expiry_pair'), models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('approved_at')), _connector='OR'), name='support_grant_expires_after_approval'), models.CheckConstraint(condition=models.Q(('approved_by__isnull', True), models.Q(('approved_by', models.F('requested_by')), _negated=True), _connector='OR'), name='support_grant_not_self_approved'), models.CheckConstraint(condition=models.Q(('request_ref', ''), _negated=True), name='support_grant_has_request_ref'), models.CheckConstraint(condition=models.Q(('justification', ''), _negated=True), name='support_grant_has_justification'), models.UniqueConstraint(condition=models.Q(('approved_at__isnull', True), ('revoked_at__isnull', True)), fields=('tenant', 'requested_by'), name='support_grant_one_pending')],
            },
        ),
            run_sql_file(
            "0077_support_grant",
            up_sha256="1cbd0678f2dff698bf88d09a12594c73973ea69a0f1057f1747ceca12751eb53",
            down_sha256="37e841119850995d9956d35e62a6e16bd80e1f5f3535365b21be098cd72cd815",
        ),
    ]
