# Generated by Django 5.2.17 on 2026-08-25 07:32

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("uom", "0001_initial"),
        ("partners", "0001_initial"),
        ("counterparties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.TextField()),
                ('name', models.TextField()),
                ('kind', models.TextField(choices=[('goods', 'Goods'), ('service', 'Service'), ('product', 'Product')], default='goods')),
                ('tracks_lots', models.BooleanField(default=False)),
                ('tracks_serials', models.BooleanField(default=False)),
                ('barcode', models.TextField(blank=True, null=True)),
                ('vat_rate_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_category',
            },
        ),
    ]
