# Generated by Django 5.2.17 on 2026-08-25 07:32

import django.db.models.deletion
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('tenancy', '0005_resolver_grant'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(db_column='base_unit_id', on_delete=django.db.models.deletion.PROTECT, to='uom.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='items.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemcategory',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='items.itemcategory'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='item_category_code_unique'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='item_name_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='item_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='item_sku_unique'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['goods', 'service', 'product'])), name='item_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'service'), _negated=True), models.Q(('tracks_lots', False), ('tracks_serials', False)), _connector='OR'), name='item_service_tracks_nothing'),
        ),
        # The SQL lives here rather than in 0001: makemigrations split the
        # foreign keys into this second migration, so `tenant_id` does not exist
        # until it runs. A policy referencing a column that is one migration away
        # fails on a clean database and passes on a migrated one -- which is the
        # worst shape a schema bug can take.
        run_sql_file(
            "0025_masterdata",
            up_sha256="667e529479f9d133a7d89fe060db5462aa485e180a43205e4eae8d124c7366c3",
            down_sha256="94d5575ea6f7e43779343963cd59a32228324d74afbd1bc47f4aac0d9aaec90d",
        ),
    ]
