"""Item: alternative units, barcodes, tariff heading, internal name -- ADR-034.

REVERSIBILITY = "reversible-tested"

`item.barcode` becomes `item_barcode`: an item routinely has several codes, and a
single column left the second one nowhere to go. Pure schema (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


from evidenta.platform.rls.sql import run_sql_file

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
        ('tenancy', '0007_provision_company_privileges'),
        ('uom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBarcode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_barcode',
            },
        ),
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numerator', models.DecimalField(decimal_places=6, max_digits=20)),
                ('denominator', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_unit',
            },
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='item_kind_valid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.AddField(
            model_name='item',
            name='internal_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tariff_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.TextField(choices=[('goods', 'Goods'), ('material', 'Material'), ('product', 'Product'), ('service', 'Service'), ('low_value_short_lived', 'Low Value Short Lived')], default='goods'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'internal_name'], name='item_internal_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['goods', 'material', 'product', 'service', 'low_value_short_lived'])), name='item_kind_valid'),
        ),
        migrations.AddField(
            model_name='itembarcode',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='items.item'),
        ),
        migrations.AddField(
            model_name='itembarcode',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='itembarcode',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uom.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='item',
            field=models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uom.unitofmeasure'),
        ),
        migrations.AddIndex(
            model_name='itembarcode',
            index=models.Index(fields=['tenant', 'item'], name='item_barcode_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='itembarcode',
            constraint=models.UniqueConstraint(fields=('tenant', 'barcode'), name='item_barcode_unique'),
        ),
        migrations.AddConstraint(
            model_name='itembarcode',
            constraint=models.CheckConstraint(condition=models.Q(('barcode', ''), _negated=True), name='item_barcode_nonempty'),
        ),
        migrations.AddIndex(
            model_name='itemunit',
            index=models.Index(fields=['tenant', 'item'], name='item_unit_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.UniqueConstraint(fields=('item', 'unit'), name='item_unit_unique'),
        ),
        migrations.AddConstraint(
            model_name='itemunit',
            constraint=models.CheckConstraint(condition=models.Q(('numerator__gt', 0), ('denominator__gt', 0)), name='item_unit_positive'),
        ),
    
        run_sql_file(
            "0053_item_units_and_barcodes",
            up_sha256="9ea942a6ef02a5c712f2a69826127d98de944b88a3502360eccac54da2146319",
            down_sha256="3af92de2587ae77cb8fc2d8dbf1fcb900730ba201d086d8e6831fc9bf7475b4a",
        ),
    ]
