# Generated by Django 5.2.17 on 2026-08-25 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0001_initial'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idno', models.TextField(blank=True, null=True)),
                ('idnp', models.TextField(blank=True, null=True)),
                ('legal_name', models.TextField()),
                ('short_name', models.TextField(blank=True, null=True)),
                ('kind', models.TextField(choices=[('legal_entity', 'Legal Entity'), ('individual', 'Individual')], default='legal_entity')),
                ('vat_code', models.TextField(blank=True, null=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('addresses', models.JSONField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, null=True)),
                ('bank_accounts', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registry_entry', models.ForeignKey(blank=True, db_column='registry_entry_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='counterparties.counterpartyregistry')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='CompanyPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receivable_account_code', models.TextField(blank=True, null=True)),
                ('payable_account_code', models.TextField(blank=True, null=True)),
                ('payment_terms_days', models.SmallIntegerField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price_list_id', models.UUIDField(blank=True, null=True)),
                ('sales_agent_id', models.UUIDField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('partner', models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.PROTECT, to='partners.partner')),
            ],
            options={
                'db_table': 'company_partner',
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'legal_name'], name='partner_name_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'is_active'], name='partner_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['legal_entity', 'individual'])), name='partner_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(condition=models.Q(('idno__isnull', False)), fields=('tenant', 'idno'), name='partner_idno_unique'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.CheckConstraint(condition=models.Q(('is_customer', True), ('is_supplier', True), _connector='OR'), name='partner_has_a_role'),
        ),
        migrations.AddIndex(
            model_name='companypartner',
            index=models.Index(fields=['company', 'is_blocked'], name='company_partner_idx'),
        ),
        migrations.AddConstraint(
            model_name='companypartner',
            constraint=models.UniqueConstraint(fields=('company', 'partner'), name='company_partner_unique'),
        ),
        migrations.AddConstraint(
            model_name='companypartner',
            constraint=models.CheckConstraint(condition=models.Q(('payment_terms_days__isnull', True), ('payment_terms_days__gte', 0), _connector='OR'), name='company_partner_terms_valid'),
        ),
        migrations.AddConstraint(
            model_name='companypartner',
            constraint=models.CheckConstraint(condition=models.Q(('is_blocked', False), ('block_reason__isnull', False), _connector='OR'), name='company_partner_block_has_reason'),
        ),
    ]
