"""Partner: VAT registration as dated state, plus the internal name -- ADR-034.

REVERSIBILITY = "reversible-tested"

`partner.vat_code` moves into `partner_vat_registration` rather than being
duplicated: the code belongs to the registration, and a partner struck off and
registered again receives a new one. Pure schema; no posted data (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 07:41

import django.contrib.postgres.constraints
import django.db.models.deletion
import evidenta.masterdata.partners.models
import uuid
from django.db import migrations, models


from evidenta.platform.rls.sql import run_sql_file

class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
        ('partners', '0001_initial'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerVatRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vat_code', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partner_vat_registration',
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='vat_code',
        ),
        migrations.AddField(
            model_name='partner',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='default_payment_terms_days',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='internal_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['tenant', 'internal_name'], name='partner_internal_name_idx'),
        ),
        migrations.AddField(
            model_name='partnervatregistration',
            name='partner',
            field=models.ForeignKey(db_column='partner_id', on_delete=django.db.models.deletion.PROTECT, related_name='vat_registrations', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='partnervatregistration',
            name='tenant',
            field=models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddIndex(
            model_name='partnervatregistration',
            index=models.Index(fields=['tenant', 'partner'], name='partner_vat_reg_idx'),
        ),
        migrations.AddIndex(
            model_name='partnervatregistration',
            index=models.Index(fields=['vat_code'], name='partner_vat_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnervatregistration',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='partner_vat_registration_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnervatregistration',
            constraint=models.CheckConstraint(condition=models.Q(('vat_code', ''), _negated=True), name='partner_vat_registration_has_a_code'),
        ),
        migrations.AddConstraint(
            model_name='partnervatregistration',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('partner', '='), (evidenta.masterdata.partners.models.ValidityRange(), '&&')], name='partner_vat_registration_no_overlap'),
        ),
    
        run_sql_file(
            "0052_partner_vat_registration",
            up_sha256="96273465b9f7164cb448bb8462439397acf7c30eb8650e4fe9623c901c880642",
            down_sha256="b12b83c99bfcdc86fe009ab0f5bb4d136fbcdfad1d0c55e826fcba5f5a4b0ba8",
        ),
    ]
