"""The settlement link -- ADR-087.

REVERSIBILITY = "reversible-tested"

One table for both sides, and no trigger: a settlement is not the content of a
document, it is a link between two, written after both are posted -- which is
exactly when a "content follows its document" trigger would refuse it.

`INSERT` and `SELECT` only. A deleted settlement would make an invoice's open
balance grow back with nothing recording that somebody decided so; the correction
is a settlement the other way, when that exists.
"""

# Generated by Django 5.2.17 on 2026-08-31 20:10

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_rate_term'),
        ('tenancy', '0011_provision_company_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('side', models.TextField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')])),
                ('partner_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('settlement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('movement_document', models.ForeignKey(db_column='movement_document_id', on_delete=django.db.models.deletion.PROTECT, related_name='settlements_given', to='documents.document')),
                ('settled_document', models.ForeignKey(db_column='settled_document_id', on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to='documents.document')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'settlement',
                'indexes': [models.Index(fields=['tenant', 'company', 'settled_document'], name='settlement_settled_idx'), models.Index(fields=['company', 'partner_id'], name='settlement_partner_idx'), models.Index(fields=['tenant', 'company', 'movement_document'], name='settlement_movement_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('side__in', ['receivable', 'payable'])), name='settlement_side_valid'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_positive'), models.CheckConstraint(condition=models.Q(('settled_document', models.F('movement_document')), _negated=True), name='settlement_two_documents')],
            },
        ),
        
        run_sql_file(
            "0074_settlements",
            up_sha256="803c0fcb45bbca178012f3c1743c309de723e5942b9cf30cc8048caa74f23984",
            down_sha256="8030ad0fa2f073ff60c0dbad2c8219d9c83735da07a485f9214791fbb3cd44a2",
        ),
    ]
