"""Helpers for applying hand-written SQL from Django migrations.

See docs/decisions/012-sql-in-django-migrations.md.

A Django migration is a record of what was applied. Reading SQL from a file at
apply time breaks that property: edit the file afterwards and the recorded
migration no longer matches it, silently. Every helper here exists to turn that
silence into a loud failure.

Three rules, enforced structurally rather than by review:

1. The migration carries the SHA-256 of the SQL it applied. Verification happens
   when the migration module is imported -- that is, wherever Django builds the
   migration graph: ``migrate``, ``makemigrations``, ``showmigrations``,
   ``sqlmigrate``, and the test suite. Measured, not assumed: ``check`` does
   *not* load migrations, so it is not a fast gate for this.
2. SQL files are append-only once referenced by an applied migration. A fix is a
   new file and a new migration -- the same rule as the ledger, for the same
   reason.
3. Every forward file requires its ``.down.sql`` counterpart. A migration that
   creates a policy cannot be committed without the statement that withdraws it.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from django.db import migrations

# infra/ sits beside backend/ in the repository.
SQL_ROOT = Path(__file__).resolve().parents[4] / "infra" / "migrations"


class SqlFileChangedError(RuntimeError):
    """A SQL file changed after a migration recorded its checksum."""


class SqlFileMissingError(RuntimeError):
    """A referenced SQL file, or its required counterpart, does not exist."""


def _read(path: Path, expected_sha256: str) -> str:
    if not path.is_file():
        raise SqlFileMissingError(
            f"{path} is missing. SQL files referenced by a migration are "
            f"append-only: they are never deleted or renamed."
        )

    body = path.read_bytes()
    actual = hashlib.sha256(body).hexdigest()
    if actual != expected_sha256:
        raise SqlFileChangedError(
            f"{path} changed after the migration referencing it was written.\n"
            f"  recorded: {expected_sha256}\n"
            f"  on disk:  {actual}\n"
            f"SQL files are append-only once applied. Do not edit this file to "
            f"match: write a new file and a new migration, so the history keeps "
            f"showing what actually ran."
        )
    return body.decode("utf-8")


def run_sql_file(name: str, *, up_sha256: str, down_sha256: str) -> migrations.RunSQL:
    """Return a ``RunSQL`` operation for the ``name`` pair, checksum-verified.

    Expects ``infra/migrations/<name>.up.sql`` and ``<name>.down.sql``. The
    reverse file is not optional: without it the migration is irreversible, and
    an irreversible policy migration cannot be rolled back with the table it
    protects -- which is the whole point of putting them in one transaction.
    """
    up = _read(SQL_ROOT / f"{name}.up.sql", up_sha256)
    down = _read(SQL_ROOT / f"{name}.down.sql", down_sha256)
    return migrations.RunSQL(sql=up, reverse_sql=down)


def sha256_of(name: str, direction: str = "up") -> str:
    """Checksum for ``infra/migrations/<name>.<direction>.sql``.

    Convenience for writing a new migration; not used at apply time.
    """
    return hashlib.sha256((SQL_ROOT / f"{name}.{direction}.sql").read_bytes()).hexdigest()
