"""The register of state-issued form ranges -- art. 118 index 2 Cod fiscal.

REVERSIBILITY = "reversible-tested"

Pure schema: two tables, their policies and one trigger. It touches no posted
data, so the reverse runs and is exercised rather than asserted (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 00:42

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrictFormAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type_code', models.TextField()),
                ('series', models.TextField()),
                ('first_number', models.BigIntegerField()),
                ('last_number', models.BigIntegerField()),
                ('next_number', models.BigIntegerField()),
                ('issued_on', models.DateField()),
                ('source_reference', models.TextField()),
                ('responsible_user_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strict_form_allocation',
            },
        ),
        migrations.CreateModel(
            name='StrictFormNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.BigIntegerField()),
                ('state', models.TextField(choices=[('consumed', 'Consumed'), ('cancelled', 'Cancelled'), ('damaged', 'Damaged'), ('returned', 'Returned')])),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_by_user_id', models.UUIDField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(db_column='allocation_id', on_delete=django.db.models.deletion.PROTECT, related_name='numbers', to='strictforms.strictformallocation')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strict_form_number',
            },
        ),
        migrations.AddIndex(
            model_name='strictformallocation',
            index=models.Index(fields=['tenant', 'company', 'form_type_code'], name='strict_form_alloc_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='strictformallocation',
            constraint=models.CheckConstraint(condition=models.Q(('first_number__lte', models.F('last_number'))), name='strict_form_allocation_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='strictformallocation',
            constraint=models.CheckConstraint(condition=models.Q(('next_number__gte', models.F('first_number')), ('next_number__lte', django.db.models.expressions.CombinedExpression(models.F('last_number'), '+', models.Value(1)))), name='strict_form_allocation_cursor_in_range'),
        ),
        migrations.AddConstraint(
            model_name='strictformallocation',
            constraint=models.CheckConstraint(condition=models.Q(('first_number__gt', 0)), name='strict_form_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='strictformallocation',
            constraint=models.UniqueConstraint(fields=('company', 'form_type_code', 'series', 'first_number'), name='strict_form_allocation_unique'),
        ),
        migrations.AddIndex(
            model_name='strictformnumber',
            index=models.Index(fields=['tenant', 'company', 'state'], name='strict_form_number_state_idx'),
        ),
        migrations.AddIndex(
            model_name='strictformnumber',
            index=models.Index(fields=['document_id'], name='strict_form_number_doc_idx'),
        ),
        migrations.AddConstraint(
            model_name='strictformnumber',
            constraint=models.UniqueConstraint(fields=('allocation', 'number'), name='strict_form_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='strictformnumber',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['consumed', 'cancelled', 'damaged', 'returned'])), name='strict_form_number_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='strictformnumber',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'consumed'), _negated=True), ('document_id__isnull', False), _connector='OR'), name='strict_form_number_consumed_names_document'),
        ),
        run_sql_file(
            "0048_strict_forms",
            up_sha256="b477d24b631b699297a29cfca29083aae306e0f55bc5e57e120b87363578b36b",
            down_sha256="a15f5f6df0d690e9b7ce037c1d9849d5d06af5ae8f20def18481e914183d00c1",
        ),
    ]
