# Generated by Django 5.2.17 on 2026-08-25 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.TextField(unique=True)),
                ('original_filename', models.TextField()),
                ('content_type', models.TextField()),
                ('byte_size', models.BigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('uploaded_by_user_id', models.UUIDField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('document', models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='documents.document')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'attachment_metadata',
                'indexes': [models.Index(fields=['tenant', 'company', 'uploaded_at'], name='attachment_scope_idx'), models.Index(fields=['document'], name='attachment_document_idx'), models.Index(fields=['company', 'checksum_sha256'], name='attachment_checksum_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='attachment_size_positive'), models.CheckConstraint(condition=models.Q(('checksum_sha256__regex', '^[0-9a-f]{64}$')), name='attachment_checksum_shape')],
            },
        ),
            run_sql_file(
            "0031_attachments",
            up_sha256="7bbf02e3697e7b4059af0dce9098613b827d5312fe344e9a40bd1f4c18501fbe",
            down_sha256="a6cfdcebf8df722579307e4f38ba96cf57fd28033e480c4bf4750b4b4c5b14cd",
        ),
    ]
