# Generated by Django 5.2.17 on 2026-08-25 07:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalParameterSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('act_type', models.TextField()),
                ('act_number', models.TextField()),
                ('official_gazette_number', models.TextField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField()),
                ('url', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fiscal_parameter_source',
                'indexes': [models.Index(fields=['act_number'], name='fiscal_source_act_idx')],
            },
        ),
        migrations.CreateModel(
            name='FiscalParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameter_key', models.TextField()),
                ('scope', models.TextField(choices=[('global', 'Global'), ('company_class', 'Company Class'), ('company', 'Company')], default='global')),
                ('scope_ref', models.UUIDField(blank=True, null=True)),
                ('value_type', models.TextField(choices=[('decimal', 'Decimal'), ('integer', 'Integer'), ('money', 'Money'), ('percentage', 'Percentage'), ('date', 'Date'), ('boolean', 'Boolean'), ('table', 'Table')])),
                ('value', models.JSONField()),
                ('unit', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('superseded', 'Superseded')], default='draft')),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.PROTECT, to='fiscal_parameters.fiscalparametersource')),
            ],
            options={
                'db_table': 'fiscal_parameter',
                'indexes': [models.Index(fields=['parameter_key', 'valid_from'], name='fiscal_parameter_key_idx'), models.Index(fields=['status'], name='fiscal_parameter_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='fiscal_parameter_period_valid'), models.CheckConstraint(condition=models.Q(('scope__in', ['global', 'company_class', 'company'])), name='fiscal_parameter_scope_valid'), models.CheckConstraint(condition=models.Q(('value_type__in', ['decimal', 'integer', 'money', 'percentage', 'date', 'boolean', 'table'])), name='fiscal_parameter_value_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'approved', 'active', 'superseded'])), name='fiscal_parameter_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('scope', 'global'), ('scope_ref__isnull', True)), models.Q(('scope', 'global'), _negated=True), _connector='OR'), name='fiscal_parameter_global_has_no_ref'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('approved_by_user_id__isnull', False), _connector='OR'), name='fiscal_parameter_active_requires_approval')],
            },
        ),
    ]
