"""A margin has to say what establishes it -- `OD-92`, ADR-070 section 3.

REVERSIBILITY = "irreversible"

**What this enforces.** ``valid_from`` is a *margin*: the date an amending act's
final article establishes. A redaction shows only that a value was in force at
some point inside its interval, so writing the redaction's date here is a
fabricated margin -- right as a value, invented as an interval, and nothing ever
compares it to anything.

**And what it deliberately does not enforce.** ``valid_from`` becomes nullable.
The prohibition is on a margin *without a source*, not on an absent margin: rows
whose margin was never established -- the 24% total and the 18/6 split at point
1.5 of annex 1 to Law 489/1999 have no citable act -- must stay writable, or
whoever needs them invents a margin. That is the defect, produced by its own
enforcement.

**The backfill moves data rather than deleting it, and that is the point.**
Twenty-four rows carry a `valid_from` that no read clause establishes; one of
them says so in its own reason (*"Data 01.01.2021 e afirmată, clauza necitită"*).
Those dates are **observations**, not margins, so they move to ``observed_in``
and ``valid_from`` becomes NULL. Nothing is lost: what was known is still
recorded, in the column that matches what it is. Every one of the twenty-four has
a `provisional_reason` already -- measured before writing -- so the companion
CHECK is satisfied without inventing text.

The two platform conventions are the exception the specification did not cover
and the reason `MarginBasis` has two values: their margin *is* sourced, by a
decision rather than by a law (ADR-037). Forcing them to claim an act would be
the same fabrication from the other side.

**Irreversible, and the reverse does not even get far.** The four constraint
reversals and the backfill's noop reverse succeed trivially, but the next
reversed operation puts `NOT NULL` back on `valid_from`, which PostgreSQL refuses
wherever the backfill left a NULL. So this does not roll the schema back while
losing the meaning -- it **aborts partway**. Both halves are the point: the
meaning would not survive a reverse anyway, because putting an asserted date back
into `valid_from` would re-fabricate the margin this exists to remove.

**Two keys, named rather than matched by prefix.** An earlier draft split the
backfill on `parameter_key LIKE 'accounting.%'`. That would silently label a
future, genuinely act-sourced `accounting.*` row as a platform convention and
attach an ADR-037 citation it never earned -- a fabricated margin, produced by
the migration that exists to forbid fabricated margins. The two conventions are
listed by name; anything else keeps its observation.
"""

# Generated by Django 5.2.17 on 2026-08-30 14:03

import django.db.models.deletion
from django.db import migrations, models


#: The backfill runs as SQL with `FORCE ROW LEVEL SECURITY` suspended for the
#: length of the migration's transaction, and both halves of that need saying.
#:
#: **Why it is needed:** `fiscal_parameter` has two policies -- read for
#: `evidenta_app`, all for `evidenta_refdata` -- and none for the owner, while
#: FORCE applies to the owner too. A migration running as `evidenta_owner`
#: therefore sees **zero rows**, so the first version of this backfill iterated
#: nothing, saved nothing, and reported success; the constraint then failed on
#: the rows it was supposed to have fixed. Measured, not assumed.
#:
#: **Why not the 0044 precedent:** that added a permanent owner-write policy to
#: `coa_template`. Doing the same here would widen who may write
#: `fiscal_parameter` for ever, and ADR-049 with `R5` makes `evidenta_refdata`
#: its **exclusive** writer. A one-off data move does not get to contradict an
#: accepted ADR quietly. Suspending FORCE inside this transaction changes no
#: steady state: it rolls back with everything else if the migration fails, and
#: the table leaves the migration exactly as it entered it.
BACKFILL = """
ALTER TABLE fiscal_parameter NO FORCE ROW LEVEL SECURITY;

UPDATE fiscal_parameter
   SET margin_basis = 'platform_convention',
       margin_reference = 'ADR-037 §3.2 — convenție de platformă, aprobată de proprietar'
 WHERE parameter_key IN ('accounting.amount_scale', 'accounting.unit_price_scale');

UPDATE fiscal_parameter
   SET observed_in = 'Data ' || valid_from::text || ' a fost scrisă ca `valid_from` înainte de '
                  || '`OD-92`, fără ca articolul final care o stabilește să fi fost citit. '
                  || 'Păstrată aici ca observație: valoarea apare în actul citat, marginea '
                  || 'rămâne nestabilită.',
       valid_from = NULL
 WHERE parameter_key NOT IN ('accounting.amount_scale', 'accounting.unit_price_scale')
   AND valid_from IS NOT NULL;

ALTER TABLE fiscal_parameter FORCE ROW LEVEL SECURITY;
"""

#: Deliberately not the inverse -- see the module docstring. Restoring the dates
#: would re-fabricate the margins this migration exists to remove.
BACKFILL_REVERSE = migrations.RunSQL.noop


class Migration(migrations.Migration):
    dependencies = [
        ("fiscal_parameters", "0006_source_act"),
        ("legislation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fiscalparameter",
            name="fiscal_parameter_period_valid",
        ),
        migrations.AddField(
            model_name="fiscalparameter",
            name="margin_act",
            field=models.ForeignKey(
                blank=True,
                db_column="margin_act_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fiscal_margins",
                to="legislation.normativeact",
            ),
        ),
        migrations.AddField(
            model_name="fiscalparameter",
            name="margin_basis",
            field=models.TextField(
                blank=True,
                choices=[("act", "Act"), ("platform_convention", "Platform Convention")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fiscalparameter",
            name="margin_reference",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiscalparameter",
            name="observed_in",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fiscalparameter",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(BACKFILL, BACKFILL_REVERSE),
        migrations.AddConstraint(
            model_name="fiscalparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="fiscal_parameter_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    models.Q(
                        ("margin_basis", "act"),
                        ("margin_act__isnull", False),
                        models.Q(("margin_reference", ""), _negated=True),
                        ("margin_reference__isnull", False),
                    ),
                    models.Q(
                        ("margin_basis", "platform_convention"),
                        models.Q(("margin_reference", ""), _negated=True),
                        ("margin_reference__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fiscal_parameter_margin_is_sourced",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", False),
                    models.Q(
                        models.Q(("provisional_reason__isnull", True), _negated=True),
                        models.Q(("provisional_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="fiscal_parameter_absent_margin_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscalparameter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "active"), _negated=True),
                    ("valid_from__isnull", False),
                    _connector="OR",
                ),
                name="fiscal_parameter_active_needs_margin",
            ),
        ),
    ]
