# Generated by Django 5.2.17 on 2026-08-25 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0006_remove_user_mfa_secret_encrypted_mfabackupcode_and_more'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilityActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability_key', models.TextField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('initialisation_state', models.TextField(choices=[('not_required', 'Not Required'), ('required', 'Required'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='not_required')),
                ('initialisation_ref', models.TextField(blank=True, null=True)),
                ('activated_at', models.DateTimeField()),
                ('source', models.TextField(choices=[('plan', 'Plan'), ('manual', 'Manual'), ('migration', 'Migration')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(db_column='activated_by_user_id', on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
                ('company', models.ForeignKey(blank=True, db_column='company_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'capability_activation',
                'indexes': [models.Index(fields=['tenant', 'capability_key', 'effective_from'], name='capability_activation_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='capability_activation_period_valid'), models.CheckConstraint(condition=models.Q(('initialisation_state__in', ['not_required', 'required', 'in_progress', 'complete'])), name='capability_activation_state_valid'), models.CheckConstraint(condition=models.Q(('source__in', ['plan', 'manual', 'migration'])), name='capability_activation_source_valid'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), models.Q(('capability_key__in', ('vat', 'efactura', 'statutory_reporting')), _negated=True), _connector='OR'), name='capability_activation_compliance_never_ends')],
            },
        ),
        run_sql_file(
            "0022_capabilities",
            up_sha256="c8ac1d42e946add434b42159680354891c19d3661afa1d7311245077b4986725",
            down_sha256="0242c0cfc35bdc87ca8171b8082135d5643787c753bdeb3795e7ced92020ae07",
        ),
    ]
