"""Purchase-side document types over the document core.

REVERSIBILITY = "reversible-tested"

The supplier's own number and date are theirs: recorded as received, never
allocated by our series, and part of the deduplication key together with the
supplier (`R20`). Pure schema (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 08:08

import django.db.models.deletion
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_layer'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='purchase', serialize=False, to='documents.document')),
                ('partner_id', models.UUIDField()),
                ('supplier_document_number', models.TextField()),
                ('supplier_document_date', models.DateField()),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'purchase_document',
                'indexes': [models.Index(fields=['tenant', 'company', 'supplier_document_date'], name='purchase_document_idx'), models.Index(fields=['company', 'partner_id'], name='purchase_document_partner_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('supplier_document_number', ''), _negated=True), name='purchase_document_has_supplier_number'), models.UniqueConstraint(fields=('company', 'partner_id', 'supplier_document_number', 'supplier_document_date'), name='purchase_document_supplier_reference_unique')],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supplier_order', serialize=False, to='documents.document')),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'supplier_order',
                'indexes': [models.Index(fields=['tenant', 'company', 'expected_delivery_date'], name='supplier_order_idx')],
            },
        ),
    
        run_sql_file(
            "0055_purchase_documents",
            up_sha256="97963be1c8551a39e4477f19e077fb45ce971ed0fcff2e97b95f7148040b33cc",
            down_sha256="996170e5051ec5f43f48d1140e0db79697aa98c558c4753c579bf154eea128c5",
        ),
    ]
