# Generated by Django 5.2.17 on 2026-08-26 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('entry_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'operation_template',
            },
        ),
        migrations.CreateModel(
            name='OperationTemplateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.IntegerField()),
                ('account_id', models.UUIDField()),
                ('side', models.TextField(choices=[('debit', 'Debit'), ('credit', 'Credit')])),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('input_key', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='posting.operationtemplate')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'operation_template_line',
            },
        ),
        migrations.CreateModel(
            name='OperationTemplateDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.TextField()),
                ('fixed_value_id', models.UUIDField(blank=True, null=True)),
                ('input_key', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('line', models.ForeignKey(db_column='line_id', on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='posting.operationtemplateline')),
            ],
            options={
                'db_table': 'operation_template_dimension',
            },
        ),
        migrations.AddIndex(
            model_name='operationtemplate',
            index=models.Index(fields=['tenant', 'company', 'is_active'], name='operation_template_company'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'name'), name='operation_template_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateline',
            constraint=models.UniqueConstraint(fields=('template', 'line_number'), name='operation_template_line_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateline',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['debit', 'credit'])), name='operation_template_line_side_valid'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateline',
            constraint=models.CheckConstraint(condition=models.Q(('line_number__gt', 0)), name='operation_template_line_number_valid'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_amount__isnull', True), ('input_key__isnull', False)), models.Q(('fixed_amount__isnull', False), ('input_key__isnull', True)), _connector='OR'), name='operation_template_line_one_amount_source'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplateline',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_amount__isnull', True), ('fixed_amount__gt', 0), _connector='OR'), name='operation_template_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplatedimension',
            constraint=models.UniqueConstraint(fields=('line', 'dimension'), name='operation_template_dimension_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplatedimension',
            constraint=models.CheckConstraint(condition=models.Q(('dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5'])), name='operation_template_dimension_known'),
        ),
        migrations.AddConstraint(
            model_name='operationtemplatedimension',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_value_id__isnull', True), ('input_key__isnull', False)), models.Q(('fixed_value_id__isnull', False), ('input_key__isnull', True)), _connector='OR'), name='operation_template_dimension_one_source'),
        ),
        # Table and policy in the same transaction -- C30. The composite keys
        # that stop a line from drifting to another company, the byte collation
        # on the input keys, the three policies and the grants cannot be
        # expressed in Django; and a policy one migration away from the table it
        # protects fails on a clean database and passes on a migrated one.
        run_sql_file(
            "0040_operation_templates",
            up_sha256="b77ee4bca4d897574d31186b43973ca05ec78afff735b49a3e3d831391503348",
            down_sha256="091e3309cfb5e0667396cc23ae0db914260ce83060fb2c3feb0c4074835d949c",
        ),
    ]
