# Generated by Django 5.2.17 on 2026-08-25 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0007_session_token'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_key', models.TextField()),
                ('params', models.JSONField(default=dict)),
                ('company_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_user', models.ForeignKey(db_column='recipient_user_id', on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.TextField(choices=[('in_app', 'In App'), ('email', 'Email')])),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unavailable', 'Unavailable')], default='pending')),
                ('attempts', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='notifications.notification')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'notification_delivery',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'recipient_user', 'created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='notification_delivery_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='notification_delivery_unique'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['in_app', 'email'])), name='notification_delivery_channel_valid'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'sent', 'failed', 'unavailable'])), name='notification_delivery_status_valid'),
        ),
            run_sql_file(
            "0030_notifications",
            up_sha256="e9a016811908ecd582ea1f802cd8d8ed18643e443b3b1cfc7a37da1471828873",
            down_sha256="17efb9f841906e53eeee0df7d2ba681f58a798d61ac5ceb11a53762f24d350d3",
            down_name="0030_notifications_reverse",
        ),
    ]
