# Generated by Django 5.2.17 on 2026-08-25 15:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoaTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('version', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source_act', models.TextField()),
                ('source_reference', models.TextField(blank=True, null=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('published', 'Published'), ('superseded', 'Superseded')], default='draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coa_template',
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='coa_template_version_unique'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'superseded'])), name='coa_template_status_valid'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='coa_template_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='CoaTemplateAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.TextField()),
                ('parent_code', models.TextField(blank=True, null=True)),
                ('name_ro', models.TextField()),
                ('account_class', models.TextField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')])),
                ('normal_balance', models.TextField(choices=[('debit', 'Debit'), ('credit', 'Credit')])),
                ('is_system', models.BooleanField(default=True)),
                ('allows_subaccounts', models.BooleanField()),
                ('currency_tracking', models.BooleanField(default=False)),
                ('quantity_tracking', models.BooleanField(default=False)),
                ('required_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.PROTECT, to='coa.coatemplate')),
            ],
            options={
                'db_table': 'coa_template_account',
            },
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.TextField()),
                ('origin', models.TextField(choices=[('system', 'System'), ('company', 'Company')])),
                ('name_ro', models.TextField()),
                ('account_class', models.TextField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')])),
                ('normal_balance', models.TextField(choices=[('debit', 'Debit'), ('credit', 'Credit')])),
                ('allows_subaccounts', models.BooleanField(default=False)),
                ('currency_tracking', models.BooleanField(default=False)),
                ('quantity_tracking', models.BooleanField(default=False)),
                ('required_dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('is_blocked', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='coa.companyaccount')),
                ('template_account', models.ForeignKey(blank=True, db_column='template_account_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='coa.coatemplateaccount')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'company_account',
            },
        ),
        migrations.CreateModel(
            name='CompanyChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instantiated_at', models.DateTimeField(auto_now_add=True)),
                ('last_propagation_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.PROTECT, to='coa.coatemplate')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'company_chart',
            },
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'parent_code'], name='coa_template_parent_idx'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.UniqueConstraint(fields=('template', 'account_code'), name='coa_template_account_unique'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_class__in', ['asset', 'liability', 'equity', 'income', 'expense'])), name='coa_template_account_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('normal_balance__in', ['debit', 'credit'])), name='coa_template_account_balance_valid'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='coa_template_account_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('required_dimensions__contained_by', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5'])), name='coa_template_account_dimensions_known'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['company', 'valid_from', 'valid_to'], name='company_account_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['company', 'is_blocked'], name='company_account_blocked_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['template_account'], name='company_account_template_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.UniqueConstraint(fields=('company', 'account_code'), name='company_account_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ['system', 'company'])), name='company_account_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_class__in', ['asset', 'liability', 'equity', 'income', 'expense'])), name='company_account_class_valid'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('normal_balance__in', ['debit', 'credit'])), name='company_account_balance_valid'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origin', 'system'), _negated=True), ('template_account__isnull', False), _connector='OR'), name='company_account_system_has_template'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='company_account_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('required_dimensions__contained_by', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5'])), name='company_account_dimensions_known'),
        ),
        migrations.AddConstraint(
            model_name='companychart',
            constraint=models.UniqueConstraint(fields=('company',), name='company_chart_unique'),
        ),
        # Table and policy in the same transaction -- C30. The four tables are
        # created above, so the policies below can reference their columns; a
        # policy one migration away from the column it names fails on a clean
        # database and passes on a migrated one.
        run_sql_file(
            "0033_coa",
            up_sha256="b4305f8256074237a95897597d5e1154e5c0691c346223ff370cb498af43f0a4",
            down_sha256="33e205de53a4415c45fb784d51e3fa0c0441297397ecf5634a5e062e789749f7",
        ),
    ]
