"""The account declares which dimensions it carries -- ADR-048, stage 1+2.

REVERSIBILITY = "reversible-tested"

Four typed slot columns on `coa_template_account` and on `company_account`, the
shape constraints Django can express, and -- in the SQL file -- the collation and
the one constraint it cannot: a required dimension is one of the declared slots.
Every column arrives NULL; the declaration itself is the owner's accounting
decision and is not made here.
"""

# Generated by Django 5.2.17 on 2026-08-28 23:30

from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_reference_load_policy'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='coatemplateaccount',
            name='slot_1_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='slot_2_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='slot_3_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='slot_4_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='slot_1_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='slot_2_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='slot_3_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='slot_4_dimension',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension__isnull', True), ('slot_1_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='coa_template_account_slot_1_known'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension__isnull', True), ('slot_2_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='coa_template_account_slot_2_known'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension__isnull', True), ('slot_1_dimension__isnull', False), _connector='OR'), name='coa_template_account_slot_2_contiguous'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_3_dimension__isnull', True), ('slot_3_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='coa_template_account_slot_3_known'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_3_dimension__isnull', True), ('slot_2_dimension__isnull', False), _connector='OR'), name='coa_template_account_slot_3_contiguous'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_4_dimension__isnull', True), ('slot_4_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='coa_template_account_slot_4_known'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_4_dimension__isnull', True), ('slot_3_dimension__isnull', False), _connector='OR'), name='coa_template_account_slot_4_contiguous'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_2_dimension')), _negated=True), name='coa_template_account_slot_1_2_distinct'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_3_dimension')), _negated=True), name='coa_template_account_slot_1_3_distinct'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_4_dimension')), _negated=True), name='coa_template_account_slot_1_4_distinct'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension', models.F('slot_3_dimension')), _negated=True), name='coa_template_account_slot_2_3_distinct'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension', models.F('slot_4_dimension')), _negated=True), name='coa_template_account_slot_2_4_distinct'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_3_dimension', models.F('slot_4_dimension')), _negated=True), name='coa_template_account_slot_3_4_distinct'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension__isnull', True), ('slot_1_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='company_account_slot_1_known'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension__isnull', True), ('slot_2_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='company_account_slot_2_known'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension__isnull', True), ('slot_1_dimension__isnull', False), _connector='OR'), name='company_account_slot_2_contiguous'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_3_dimension__isnull', True), ('slot_3_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='company_account_slot_3_known'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_3_dimension__isnull', True), ('slot_2_dimension__isnull', False), _connector='OR'), name='company_account_slot_3_contiguous'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_4_dimension__isnull', True), ('slot_4_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='company_account_slot_4_known'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_4_dimension__isnull', True), ('slot_3_dimension__isnull', False), _connector='OR'), name='company_account_slot_4_contiguous'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_2_dimension')), _negated=True), name='company_account_slot_1_2_distinct'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_3_dimension')), _negated=True), name='company_account_slot_1_3_distinct'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_4_dimension')), _negated=True), name='company_account_slot_1_4_distinct'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension', models.F('slot_3_dimension')), _negated=True), name='company_account_slot_2_3_distinct'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_2_dimension', models.F('slot_4_dimension')), _negated=True), name='company_account_slot_2_4_distinct'),
        ),
        migrations.AddConstraint(
            model_name='companyaccount',
            constraint=models.CheckConstraint(condition=models.Q(('slot_3_dimension', models.F('slot_4_dimension')), _negated=True), name='company_account_slot_3_4_distinct'),
        ),
            run_sql_file(
            "0056_dimension_slots",
            up_sha256="193f3cf5623fee40e1c78199cbccfb401974e46c1574248eff260a72474a8885",
            down_sha256="258e01973b026b5928f9558770b71cf42401412be7983643945379cff4a9e6ee",
        ),
    ]
