# Generated by Django 5.2.17 on 2026-08-25 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('tenancy', '0003_tenant_context_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('idno', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'firm',
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('transferred', 'Transferred')], default='invited')),
                ('covers_all_companies', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('initiated_by', models.TextField()),
                ('invited_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, db_column='accepted_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagements_accepted', to='identity.user')),
                ('client_tenant', models.ForeignKey(db_column='client_tenant_id', on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='tenancy.tenant')),
                ('invited_by', models.ForeignKey(db_column='invited_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='engagements_invited', to='identity.user')),
                ('revoked_by', models.ForeignKey(blank=True, db_column='revoked_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='engagements_revoked', to='identity.user')),
                ('transferred_to', models.ForeignKey(blank=True, db_column='transferred_to_engagement_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferred_from', to='engagement.engagement')),
                ('firm', models.ForeignKey(db_column='firm_id', on_delete=django.db.models.deletion.PROTECT, to='engagement.firm')),
            ],
            options={
                'db_table': 'engagement',
            },
        ),
        migrations.CreateModel(
            name='EngagementCompanyScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_tenant', models.ForeignKey(db_column='client_tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('engagement', models.ForeignKey(db_column='engagement_id', on_delete=django.db.models.deletion.CASCADE, to='engagement.engagement')),
            ],
            options={
                'db_table': 'engagement_company_scope',
                'indexes': [models.Index(fields=['company'], name='eng_company_scope_comp_idx')],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'company'), name='engagement_company_scope_unique')],
            },
        ),
        migrations.CreateModel(
            name='EngagementModuleScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_key', models.TextField()),
                ('permission_level', models.TextField()),
                ('engagement', models.ForeignKey(db_column='engagement_id', on_delete=django.db.models.deletion.CASCADE, to='engagement.engagement')),
            ],
            options={
                'db_table': 'engagement_module_scope',
                'constraints': [models.UniqueConstraint(fields=('engagement', 'module_key'), name='engagement_module_scope_unique'), models.CheckConstraint(condition=models.Q(('permission_level__in', ['read', 'write'])), name='engagement_module_scope_level_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='firm',
            index=models.Index(fields=['status'], name='firm_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='firm',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'closed'])), name='firm_status_valid'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['client_tenant', 'status'], name='engagement_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['firm', 'status'], name='engagement_firm_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='engagement_validity_ordered'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('accepted_at__isnull', False), _connector='OR'), name='engagement_active_requires_acceptance'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'revoked'), _negated=True), ('revoked_at__isnull', False), _connector='OR'), name='engagement_revoked_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['invited', 'active', 'suspended', 'revoked', 'expired', 'transferred'])), name='engagement_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.CheckConstraint(condition=models.Q(('initiated_by__in', ['firm', 'tenant'])), name='engagement_initiated_by_valid'),
        ),
        migrations.AddConstraint(
            model_name='engagement',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('invited', 'active', 'suspended'))), fields=('firm', 'client_tenant'), name='engagement_live_unique'),
        ),
        # ADR-012: tabela și politica ei, în aceeași tranzacție.
        run_sql_file(
            "0013_engagement",
            up_sha256="fdf7160a9b4e65118ce7e4875488b27bf572381f8cfaa18e2f9eb9e9bcf5d9ef",
            down_sha256="5ffd1ba6e2afbd12a6bfb991ffdb32e69f4653219b88a03140cf0061dc567201",
        ),
    ]
