# Generated by Django 5.2.17 on 2026-08-25 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.TextField(blank=True, null=True)),
                ('series', models.TextField(default='')),
                ('prefix', models.TextField(default='')),
                ('suffix', models.TextField(default='')),
                ('separator', models.TextField(default='')),
                ('digits', models.SmallIntegerField(default=6)),
                ('include_year', models.BooleanField(default=True)),
                ('year_format', models.TextField(choices=[('yyyy', 'Four Digit'), ('yy', 'Two Digit')], default='yyyy')),
                ('reset_policy', models.TextField(choices=[('never', 'Never'), ('yearly', 'Yearly'), ('monthly', 'Monthly')], default='yearly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'numbering_template',
            },
        ),
        migrations.CreateModel(
            name='NumberingCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_key', models.TextField()),
                ('next_number', models.BigIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('template', models.ForeignKey(db_column='template_id', on_delete=django.db.models.deletion.PROTECT, to='numbering.numberingtemplate')),
            ],
            options={
                'db_table': 'numbering_counter',
            },
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('digits__gte', 1), ('digits__lte', 12)), name='numbering_template_digits_valid'),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('reset_policy__in', ['never', 'yearly', 'monthly'])), name='numbering_template_reset_valid'),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('year_format__in', ['yyyy', 'yy'])), name='numbering_template_year_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type__isnull', False)), fields=('company', 'document_type'), name='numbering_template_per_type_unique'),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type__isnull', True)), fields=('company',), name='numbering_template_general_unique'),
        ),
        migrations.AddConstraint(
            model_name='numberingcounter',
            constraint=models.UniqueConstraint(fields=('template', 'period_key'), name='numbering_counter_unique'),
        ),
        migrations.AddConstraint(
            model_name='numberingcounter',
            constraint=models.CheckConstraint(condition=models.Q(('next_number__gte', 1)), name='numbering_counter_positive'),
        ),
    ]
