"""Document series: the two numbering regimes, and validity over time -- ADR-022.

REVERSIBILITY = "reversible-tested"

`valid_from` arrives nullable, is backfilled from `created_at`, and is then made
NOT NULL -- the backfill is in the SQL file so the failure is loud if a row
somehow has no date. Pure schema; no posted data (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 07:41

import django.contrib.postgres.constraints
import evidenta.platform.numbering.models
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('numbering', '0001_initial'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='numberingtemplate',
            name='numbering_template_per_type_unique',
        ),
        migrations.RemoveConstraint(
            model_name='numberingtemplate',
            name='numbering_template_general_unique',
        ),
        migrations.AddField(
            model_name='numberingtemplate',
            name='regime',
            field=models.TextField(choices=[('own', 'Own'), ('external', 'External')], default='own'),
        ),
        migrations.AddField(
            model_name='numberingtemplate',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='numberingtemplate',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        run_sql_file(
            "0050_numbering_series",
            up_sha256="cb7c00bdf3a05a0e54aeb096a971ce26fc9e0225f12797c52b98f528c66931b0",
            down_sha256="67b869d2a8d3971f37e1257b80689998e2ddfd29192f7e86552c09e1b3b727b4",
        ),
        # After the backfill, never before: `SET NOT NULL` scans the table
        # physically rather than through the policy, so a row the owner cannot
        # see still fails it -- which is the loud answer, not a silent one.
        migrations.AlterField(
            model_name='numberingtemplate',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('regime__in', ['own', 'external'])), name='numbering_template_regime_valid'),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='numbering_template_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='numberingtemplate',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('company', '='), (evidenta.platform.numbering.models.TypeKey(), '='), (evidenta.platform.numbering.models.ValidityRange(), '&&')], name='numbering_template_no_overlap'),
        ),
    ]
