# Generated by Django 5.2.17 on 2026-08-25 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('decimal_places', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'unit_of_measure',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numerator', models.DecimalField(decimal_places=6, max_digits=20)),
                ('denominator', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('from_unit', models.ForeignKey(db_column='from_unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='conversions_from', to='uom.unitofmeasure')),
                ('to_unit', models.ForeignKey(db_column='to_unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='conversions_to', to='uom.unitofmeasure')),
            ],
            options={
                'db_table': 'unit_conversion',
            },
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unit_of_measure_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitofmeasure',
            constraint=models.CheckConstraint(condition=models.Q(('decimal_places__gte', 0), ('decimal_places__lte', 6)), name='unit_of_measure_decimals_valid'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('from_unit', 'to_unit'), name='unit_conversion_unique'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.CheckConstraint(condition=models.Q(('numerator__gt', 0), ('denominator__gt', 0)), name='unit_conversion_positive'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.CheckConstraint(condition=models.Q(('from_unit', models.F('to_unit')), _negated=True), name='unit_conversion_not_self'),
        ),
    ]
