# Generated by Django 5.2.17 on 2026-08-25 01:05

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.TextField()),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_secret_encrypted', models.BinaryField(blank=True, null=True)),
                ('locale', models.TextField(default='ro')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'indexes': [models.Index(fields=['is_active'], name='user_is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('status', models.TextField(choices=[('invited', 'Invited'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='invited')),
                ('invited_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('invited_by', models.ForeignKey(blank=True, db_column='invited_by_user_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memberships_invited', to='identity.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
            ],
            options={
                'db_table': 'membership',
                'indexes': [models.Index(fields=['user', 'status'], name='membership_user_status_idx'), models.Index(fields=['tenant', 'status'], name='membership_tenant_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'removed'), _negated=True), fields=('tenant', 'user'), name='membership_live_unique'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), ('accepted_at__isnull', False), _connector='OR'), name='membership_active_requires_acceptance'), models.CheckConstraint(condition=models.Q(('status__in', ['invited', 'active', 'suspended', 'removed'])), name='membership_status_valid')],
            },
        ),
        # ADR-012: tabela și politica ei, în aceeași tranzacție.
        run_sql_file(
            "0011_identity",
            up_sha256="676a6ecf4c6fb10608b95b8fd96dfbfd574a964b4209444950362751591290ff",
            down_sha256="ad30f0aeb1d91866baf60eced06052197d7ef3c3a0113a62976e4d7f366a0e02",
        ),
    ]
