# Generated by Django 5.2.17 on 2026-08-25 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('identity', '0001_initial'),
        ('tenancy', '0003_tenant_context_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('granted_via', models.TextField(choices=[('membership', 'Membership'), ('engagement', 'Engagement')])),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('engagement', models.ForeignKey(blank=True, db_column='engagement_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='engagement.engagement')),
                ('granted_by', models.ForeignKey(db_column='granted_by_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='company_access_granted', to='identity.user')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='company_access', to='identity.user')),
            ],
            options={
                'db_table': 'company_access',
                'indexes': [models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user', 'company'], name='company_access_live_idx'), models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['engagement'], name='company_access_engagement_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('engagement__isnull', False), ('granted_via', 'engagement')), models.Q(('engagement__isnull', True), ('granted_via', 'membership')), _connector='OR'), name='company_access_engagement_consistency'), models.CheckConstraint(condition=models.Q(('granted_via__in', ['membership', 'engagement'])), name='company_access_granted_via_valid'), models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('company', 'user', 'granted_via'), name='company_access_live_unique')],
            },
        ),
        run_sql_file(
            "0014_company_access",
            up_sha256="bac73adf62979849f812a981e846771263de412294c8a8791cbcc87670fe7cd4",
            down_sha256="5a1e86c9d7736930164116b981a0c66884995910f2a2711385d9dcf60657574c",
            down_name="0014_company_access_reverse",
        ),
    ]
