# Generated by Django 5.2.17 on 2026-08-25 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.identity.permissions import PERMISSIONS
from evidenta.platform.rls.sql import run_sql_file


def sync_catalogue(apps, schema_editor):
    """Feed the permission catalogue from code -- ADR-020.

    Runs as the migration role, which is the privileged write path for this
    table: the catalogue is versioned in ``identity/permissions.py``, and a key
    that reached the table any other way would be a right with no code behind it.

    Insert-only. Removing a key is not a data fix: rows in ``role_permission``
    point at it, and dropping it silently would strip a right from every role
    that held it. That is its own migration, written when it happens.
    """
    Permission = apps.get_model("identity", "Permission")
    # `using` is not optional: migrations run on the `migration` connection, as
    # the owner, and the default manager would go to the application connection
    # -- which cannot see this transaction's table and, once it could, has no
    # write grant on the catalogue. Both refusals are correct; the bug is asking.
    on_migration = Permission.objects.using(schema_editor.connection.alias)
    for definition in PERMISSIONS:
        on_migration.update_or_create(key=definition.key, defaults={"scope": definition.scope})


def unsync_catalogue(apps, schema_editor):
    """Remove exactly the keys this migration inserted, and only if unused."""
    Permission = apps.get_model("identity", "Permission")
    Permission.objects.using(schema_editor.connection.alias).filter(
        key__in=[d.key for d in PERMISSIONS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_companyaccess'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('scope', models.TextField(choices=[('tenant', 'Tenant'), ('company', 'Company')])),
            ],
            options={
                'db_table': 'permission',
                'constraints': [models.CheckConstraint(condition=models.Q(('scope__in', ['tenant', 'company'])), name='permission_scope_valid')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField()),
                ('name', models.TextField()),
                ('level', models.TextField(choices=[('tenant', 'Tenant'), ('company', 'Company')])),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AlterField(
            model_name='companyaccess',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='identity.role'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, to='identity.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.TextField(choices=[('tenant', 'Tenant'), ('company', 'Company')])),
                ('permission', models.ForeignKey(db_column='permission_key', on_delete=django.db.models.deletion.PROTECT, to='identity.permission')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='identity.role')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'level'], name='role_tenant_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='role_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(condition=models.Q(('level__in', ['tenant', 'company'])), name='role_level_valid'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['tenant', 'role'], name='role_permission_tenant_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='role_permission_unique'),
        ),
        # ADR-012: tabela și politica ei, în aceeași tranzacție.
        run_sql_file(
            "0019_roles",
            up_sha256="c67c1ffe9aef74dfee4e89def72e53235cc3f9944fd838b8a724194b3f36cad8",
            down_sha256="bc343fc23e76f046ddfe2051046d7ecb13c6976ebbf0248c2ac8d9bc4ada9028",
        ),
        # Catalogul se alimentează după ce politicile există: scrie rolul de
        # migrare, prin `permission_platform_write`.
        migrations.RunPython(sync_catalogue, unsync_catalogue),
    ]
