# Generated by Django 5.2.17 on 2026-08-25 06:53

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_permission_grants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_secret_encrypted',
        ),
        migrations.CreateModel(
            name='MfaBackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.TextField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='backup_codes', to='identity.user')),
            ],
            options={
                'db_table': 'mfa_backup_code',
                'indexes': [models.Index(condition=models.Q(('used_at__isnull', True)), fields=['user'], name='mfa_backup_code_unused_idx')],
            },
        ),
        migrations.CreateModel(
            name='MfaMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.TextField(choices=[('totp', 'Totp')])),
                ('secret_encrypted', models.BinaryField()),
                ('label', models.TextField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='mfa_methods', to='identity.user')),
            ],
            options={
                'db_table': 'mfa_method',
                'indexes': [models.Index(condition=models.Q(('confirmed_at__isnull', False)), fields=['user'], name='mfa_method_confirmed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('method_type__in', ['totp'])), name='mfa_method_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('actor_firm_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='identity.user')),
            ],
            options={
                'db_table': 'user_session',
                'indexes': [models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['user'], name='user_session_live_idx'), models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['tenant_id', 'actor_firm_id'], name='user_session_firm_idx')],
            },
        ),
        run_sql_file(
            "0021_mfa_sessions",
            up_sha256="79800c08c72a9b472281d739ed52638cb6dd483127b1d77a797a8564b36b7dd0",
            down_sha256="31ff82ffd258604d9028d4276f2d4d94469f6d8188cb69435a9fa329810ece2d",
        ),
    ]
