# Generated by Django 5.2.17 on 2026-08-25 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0006_remove_user_mfa_secret_encrypted_mfabackupcode_and_more'),
        ('tenancy', '0005_resolver_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('default_state', models.BooleanField(default=False)),
                ('is_compliance', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feature_flag',
            },
        ),
        migrations.CreateModel(
            name='ReleaseRing',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('sequence', models.SmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'release_ring',
            },
        ),
        migrations.CreateModel(
            name='TenantReleaseRing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('assigned_by', models.ForeignKey(db_column='assigned_by_user_id', on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
                ('ring', models.ForeignKey(db_column='ring_code', on_delete=django.db.models.deletion.PROTECT, to='flags.releasering')),
                ('tenant', models.OneToOneField(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_release_ring',
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.BooleanField()),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.PROTECT, to='identity.user')),
                ('flag', models.ForeignKey(db_column='flag_key', on_delete=django.db.models.deletion.PROTECT, to='flags.featureflag')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'feature_flag_override',
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='feature_flag_override_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'flag'), name='feature_flag_override_unique')],
            },
        ),
        run_sql_file(
            "0023_flags",
            up_sha256="5fc76e8a36c384f874f739f8212e026ba4d7c9a9e3f08962524eefa0aeb4639d",
            down_sha256="e53d414a17950c2ca7c4613582196d43a45ab427a5395960c0a023516401c835",
            down_name="0023_flags_reverse",
        ),
    ]
