"""Treasury documents over the document core -- ADR-073 §5.

REVERSIBILITY = "reversible-tested"

The first two document types in the product that carry no positions, so the
amount is a column here rather than a sum of lines. The policy and the trigger
arrive with the table, in one transaction (`C30`).

What is deliberately not a column: which invoice the money settles. The posting
does not need it -- debit treasury, credit receivables, whichever receivable --
and the link is settlement, which is `F2.A3`.
"""

# Generated by Django 5.2.17 on 2026-08-31 19:30

import django.db.models.deletion
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_rate_term'),
        ('tenancy', '0011_provision_company_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasuryDocument',
            fields=[
                ('document', models.OneToOneField(db_column='document_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='treasury', serialize=False, to='documents.document')),
                ('direction', models.TextField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')])),
                ('treasury_account', models.TextField(choices=[('cash', 'Cash'), ('bank', 'Bank')])),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('partner_resident', models.BooleanField()),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'treasury_document',
                'indexes': [models.Index(fields=['tenant', 'company', 'direction'], name='treasury_document_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('direction__in', ['receipt', 'payment'])), name='treasury_document_direction_valid'), models.CheckConstraint(condition=models.Q(('treasury_account__in', ['cash', 'bank'])), name='treasury_document_account_valid'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='treasury_document_amount_positive')],
            },
        ),
        
        run_sql_file(
            "0073_treasury_documents",
            up_sha256="d101f142c49641f1c73db0ecd8cbaa1ea8d7c375d111fcfb958b504ef5c5a523",
            down_sha256="ec2b5101dfc233aeddd86d691f620b6ff1b62f8ae4ac8d389f2803d3ea0ace13",
        ),
    ]
