# Generated by Django 5.2.17 on 2026-08-25 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idno', models.TextField(unique=True)),
                ('legal_name', models.TextField()),
                ('legal_form', models.TextField(blank=True, null=True)),
                ('vat_registered', models.BooleanField(default=False)),
                ('vat_code', models.TextField(blank=True, null=True)),
                ('registered_address', models.JSONField(blank=True, null=True)),
                ('status', models.TextField(choices=[('active', 'Active'), ('struck_off', 'Struck Off'), ('unknown', 'Unknown')], default='unknown')),
                ('source', models.TextField()),
                ('source_reference', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'counterparty_registry',
                'indexes': [models.Index(fields=['legal_name'], name='counterparty_name_idx'), models.Index(fields=['status'], name='counterparty_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'struck_off', 'unknown'])), name='counterparty_registry_status_valid')],
            },
        ),
    ]
