"""The stamp a calculation leaves on itself -- `OD-68`, ADR-047.

REVERSIBILITY = "reversible-tested"

Pure schema: it creates a table, a policy and a trigger and touches no posted
data, so the reverse runs and is exercised in
``tests/schema_guard/test_reverse_sql.py`` rather than asserted (ADR-043 section 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-26 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
        ("tenancy", "0005_resolver_grant"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryParameterStamp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("parameter_id", models.UUIDField()),
                ("parameter_key", models.TextField()),
                ("effective_date", models.DateField()),
                ("confidence", models.TextField()),
                ("resolved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        db_column="company_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.company",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        db_column="journal_entry_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parameter_stamps",
                        to="ledger.journalentry",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        db_column="tenant_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "entry_parameter_stamp",
                "indexes": [
                    models.Index(
                        fields=["tenant", "company", "confidence"],
                        name="entry_param_confidence_idx",
                    ),
                    models.Index(fields=["parameter_id"], name="entry_param_parameter_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("journal_entry", "parameter_id"),
                        name="entry_parameter_stamp_unique",
                    )
                ],
            },
        ),
        run_sql_file(
            "0043_entry_parameter_stamp",
            up_sha256="a7e6c7007d47ce36d49e8df0efda1a1f6fdfa1bb7db467fc541c77b02574f1ae",
            down_sha256="c5898fbe63af19a00c696c16a036e13e922eb07b2e5d2bc51e6c21382c7ebe5d",
        ),
    ]
