"""The formula as the unit of posting, and what an entry stood on -- ADR-048.

REVERSIBILITY = "reversible-tested"

Pure schema: three nullable stamps on `journal_entry`, the `journal_formula`
table, its policy, its immutability trigger, the trigger that keeps the header's
stamps immutable after posting, and the deferred check that formulas and lines
say the same amount. No posted row is touched; the reverse drops what this
created and is round-tripped in ``tests/schema_guard/test_reverse_sql.py``
(ADR-043 section 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 23:30

import django.db.models.deletion
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0003_dimension_slots'),
        ('ledger', '0002_entry_parameter_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='chart_template',
            field=models.ForeignKey(blank=True, db_column='chart_template_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='coa.coatemplate'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='rule_ref',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JournalFormula',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('company_id', models.UUIDField()),
                ('accounting_date', models.DateField()),
                ('formula_number', models.SmallIntegerField()),
                ('debit_account_id', models.UUIDField()),
                ('credit_account_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount_currency', models.DecimalField(decimal_places=4, max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('rate_date', models.DateField()),
                ('document_date', models.DateField()),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('vat_rate_key', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('uom_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slot_1_dimension', models.TextField(blank=True, null=True)),
                ('slot_1_value_id', models.UUIDField(blank=True, null=True)),
                ('slot_2_dimension', models.TextField(blank=True, null=True)),
                ('slot_2_value_id', models.UUIDField(blank=True, null=True)),
                ('slot_3_dimension', models.TextField(blank=True, null=True)),
                ('slot_3_value_id', models.UUIDField(blank=True, null=True)),
                ('slot_4_dimension', models.TextField(blank=True, null=True)),
                ('slot_4_value_id', models.UUIDField(blank=True, null=True)),
                ('journal_entry', models.ForeignKey(db_column='journal_entry_id', on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='ledger.journalentry')),
            ],
            options={
                'db_table': 'journal_formula',
                'indexes': [models.Index(fields=['tenant_id', 'company_id', 'accounting_date'], name='journal_formula_scope_idx'), models.Index(fields=['company_id', 'debit_account_id', 'accounting_date'], name='journal_formula_debit_idx'), models.Index(fields=['company_id', 'credit_account_id', 'accounting_date'], name='journal_formula_credit_idx')],
                'constraints': [models.UniqueConstraint(fields=('journal_entry', 'formula_number'), name='journal_formula_number_unique'), models.UniqueConstraint(fields=('journal_entry', 'debit_account_id', 'credit_account_id', 'currency', 'exchange_rate', 'rate_date', 'document_date', 'vat_rate', 'vat_rate_key', 'uom_id', 'slot_1_dimension', 'slot_1_value_id', 'slot_2_dimension', 'slot_2_value_id', 'slot_3_dimension', 'slot_3_value_id', 'slot_4_dimension', 'slot_4_value_id'), name='journal_formula_merge_key', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('formula_number__gt', 0)), name='journal_formula_number_positive'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='journal_formula_amount_positive'), models.CheckConstraint(condition=models.Q(('amount_currency__gt', 0)), name='journal_formula_amount_currency_positive'), models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='journal_formula_rate_positive'), models.CheckConstraint(condition=models.Q(('debit_account_id', models.F('credit_account_id')), _negated=True), name='journal_formula_two_accounts'), models.CheckConstraint(condition=models.Q(('vat_rate__isnull', True), ('vat_rate__gte', 0), _connector='OR'), name='journal_formula_vat_rate_valid'), models.CheckConstraint(condition=models.Q(('vat_rate_key__isnull', True), ('vat_rate__isnull', False), _connector='OR'), name='journal_formula_vat_key_has_rate'), models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('uom_id__isnull', False), _connector='OR'), name='journal_formula_quantity_has_unit'), models.CheckConstraint(condition=models.Q(models.Q(('slot_1_dimension__isnull', True), ('slot_1_value_id__isnull', True)), models.Q(('slot_1_dimension__isnull', False), ('slot_1_value_id__isnull', False)), _connector='OR'), name='journal_formula_slot_1_paired'), models.CheckConstraint(condition=models.Q(('slot_1_dimension__isnull', True), ('slot_1_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='journal_formula_slot_1_known'), models.CheckConstraint(condition=models.Q(models.Q(('slot_2_dimension__isnull', True), ('slot_2_value_id__isnull', True)), models.Q(('slot_2_dimension__isnull', False), ('slot_2_value_id__isnull', False)), _connector='OR'), name='journal_formula_slot_2_paired'), models.CheckConstraint(condition=models.Q(('slot_2_dimension__isnull', True), ('slot_2_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='journal_formula_slot_2_known'), models.CheckConstraint(condition=models.Q(('slot_2_dimension__isnull', True), ('slot_1_dimension__isnull', False), _connector='OR'), name='journal_formula_slot_2_contiguous'), models.CheckConstraint(condition=models.Q(models.Q(('slot_3_dimension__isnull', True), ('slot_3_value_id__isnull', True)), models.Q(('slot_3_dimension__isnull', False), ('slot_3_value_id__isnull', False)), _connector='OR'), name='journal_formula_slot_3_paired'), models.CheckConstraint(condition=models.Q(('slot_3_dimension__isnull', True), ('slot_3_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='journal_formula_slot_3_known'), models.CheckConstraint(condition=models.Q(('slot_3_dimension__isnull', True), ('slot_2_dimension__isnull', False), _connector='OR'), name='journal_formula_slot_3_contiguous'), models.CheckConstraint(condition=models.Q(models.Q(('slot_4_dimension__isnull', True), ('slot_4_value_id__isnull', True)), models.Q(('slot_4_dimension__isnull', False), ('slot_4_value_id__isnull', False)), _connector='OR'), name='journal_formula_slot_4_paired'), models.CheckConstraint(condition=models.Q(('slot_4_dimension__isnull', True), ('slot_4_dimension__in', ['partner', 'item', 'employee', 'contract', 'warehouse', 'project', 'department', 'cost_center', 'asset', 'production_order', 'dim_1', 'dim_2', 'dim_3', 'dim_4', 'dim_5']), _connector='OR'), name='journal_formula_slot_4_known'), models.CheckConstraint(condition=models.Q(('slot_4_dimension__isnull', True), ('slot_3_dimension__isnull', False), _connector='OR'), name='journal_formula_slot_4_contiguous'), models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_2_dimension')), _negated=True), name='journal_formula_slot_1_2_distinct'), models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_3_dimension')), _negated=True), name='journal_formula_slot_1_3_distinct'), models.CheckConstraint(condition=models.Q(('slot_1_dimension', models.F('slot_4_dimension')), _negated=True), name='journal_formula_slot_1_4_distinct'), models.CheckConstraint(condition=models.Q(('slot_2_dimension', models.F('slot_3_dimension')), _negated=True), name='journal_formula_slot_2_3_distinct'), models.CheckConstraint(condition=models.Q(('slot_2_dimension', models.F('slot_4_dimension')), _negated=True), name='journal_formula_slot_2_4_distinct'), models.CheckConstraint(condition=models.Q(('slot_3_dimension', models.F('slot_4_dimension')), _negated=True), name='journal_formula_slot_3_4_distinct')],
            },
        ),
            run_sql_file(
            "0057_journal_formula",
            up_sha256="c860260ef74bb1cec3e816237a47cd644dd1d25aba8de39428b8aac57753552f",
            down_sha256="0deca6f947493fc5a3ae480644ea30957161b6c6c87c21d395d9e9f271294910",
        ),
    ]
