"""A line carries its entry's date; a posted amount carries two decimals -- ADR-059.

REVERSIBILITY = "reversible-tested"

Two CHECKs Django can express (`journal_line_amount_scale`,
`journal_formula_amount_scale`) and one trigger it cannot
(`journal_line_carries_the_entry_date`, in the SQL file). Adding a CHECK
validates every existing row, which is the point: the migration is where the
rows are looked at. On the development database (4 entries, 10 lines) and on a
suite database built from scratch there is nothing to look at; on a database
holding a four-decimal amount or a line dated off its entry's day, this refuses
to apply, and that refusal is the finding.
"""

# Generated by Django 5.2.17 on 2026-08-29 23:49

import django.db.models.functions.math
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_journal_formula'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalformula',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Round(models.F('amount'), 2))), name='journal_formula_amount_scale'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit', django.db.models.functions.math.Round(models.F('debit'), 2)), ('credit', django.db.models.functions.math.Round(models.F('credit'), 2))), name='journal_line_amount_scale'),
        ),
            run_sql_file(
            "0062_line_date_and_scale",
            up_sha256="b2c8608e0069c2c570c73e5d9524e1d3e9f1cc4bb7c344bc060628114d698385",
            down_sha256="f8da2fa607a89fa634f6619a553cdc2f7f0d76621821707c62dd1e630113f41b",
        ),
    ]
