# Generated by Django 5.2.17 on 2026-08-25 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.TextField(unique=True)),
                ('legal_name', models.TextField()),
                ('status', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('offboarding', 'Offboarding'), ('archived', 'Archived')], default='active')),
                ('default_locale', models.TextField(default='ro')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('offboarding_started_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant',
                'indexes': [models.Index(fields=['status'], name='tenant_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'offboarding', 'archived'])), name='tenant_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idno', models.TextField()),
                ('legal_name', models.TextField()),
                ('short_name', models.TextField(blank=True, null=True)),
                ('legal_form', models.TextField(blank=True, null=True)),
                ('functional_currency', models.CharField(default='MDL', max_length=3)),
                ('fiscal_year_start_month', models.SmallIntegerField(default=1)),
                ('accounting_start_date', models.DateField()),
                ('status', models.TextField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active')),
                ('registered_address', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyVatRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vat_code', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'company_vat_registration',
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='company_vat_registration_period_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tenant', 'status'], name='company_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('tenant', 'idno'), name='company_idno_unique'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('fiscal_year_start_month__gte', 1), ('fiscal_year_start_month__lte', 12)), name='company_fiscal_year_start_month_valid'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'suspended', 'closed'])), name='company_status_valid'),
        ),
        # ADR-012: tabela și politica ei ajung în aceeași tranzacție. Ordinea din
        # interiorul migrării: CREATE TABLE (mai sus) -> ENABLE -> FORCE ->
        # POLICY -> GRANT (în fișierul SQL).
        run_sql_file(
            "0010_tenancy",
            up_sha256="21a2296cdcd41281ffa17e8d70c76ba72fc3890f494dcb6406fecf4bda66ed93",
            down_sha256="6f41664e02ea33be0f54b83580c480abfe374210d4f0dae2e70e323d464a419e",
        ),
    ]
