"""CUATM and CAEM on the company -- the two codes a statutory header carries.

Nullable, and that is the honest state: neither classifier is in this repository,
so the column exists, the value arrives when somebody enters it, and a
declaration generated meanwhile says the code is missing rather than inventing
one.

Codes, so the SQL applies `COLLATE "C"` (`C34`). Django has no field-level
collation for this, which is why the pair exists at all.
"""

# Generated by Django 5.2.17 on 2026-08-30 23:34

from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='caem_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='cuatm_code',
            field=models.TextField(blank=True, null=True),
        ),
        run_sql_file(
            "0068_company_classifier_codes",
            up_sha256="7eeb7939ebc01b8d263a875c49adf89f21a149754404c773b2217417dd63d4b9",
            down_sha256="51fc6217d1e3cad7d4d14274eb0c0656fcf9329f101f9af2a7fd9ac0ce9f3dbe",
        ),
    ]
