"""What an account role means for one company -- ADR-036 section 5.1.

REVERSIBILITY = "reversible-tested"

Pure schema: one table and its policy. It touches no posted data (ADR-043 5.0).
"""

# Generated by Django 5.2.17 on 2026-08-28 06:49

import django.contrib.postgres.constraints
import django.db.models.deletion
import evidenta.accounting.slots.models
import uuid
from django.db import migrations, models

from evidenta.platform.rls.sql import run_sql_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coa', '0002_reference_load_policy'),
        ('tenancy', '0007_provision_company_privileges'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRoleBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='coa.companyaccount')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.company')),
                ('tenant', models.ForeignKey(db_column='tenant_id', on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'db_table': 'account_role_binding',
                'indexes': [models.Index(fields=['tenant', 'company', 'role'], name='account_role_binding_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='account_role_binding_dates_ordered'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('company', '='), ('role', '='), (evidenta.accounting.slots.models.DateRange(), '&&')], name='account_role_binding_no_overlap')],
            },
        ),
        run_sql_file(
            "0049_account_role_binding",
            up_sha256="1ef7d73b119d9f345ea079c9d5fb5d825092d6308bfaf21d2b8f9cd30415a759",
            down_sha256="2c0faeeb6b928b1feb012dea02d5aa72ea8e83382d50b3d09cf04f093478f657",
        ),
    ]
